<a href="https://colab.research.google.com/github/Tonry12/Data_joyx2/blob/main/276_patient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Read Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [27]:
path = "/content/drive/MyDrive/smarticu_data/work_files/"

In [48]:
data = pd.read_csv(path+"table_276.csv")
data.drop(['Unnamed: 0'], axis=1, inplace=True)
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8665 entries, 0 to 8664
Data columns (total 336 columns):
 #    Column                    Dtype
---   ------                    -----
 0    AdmissionID               int64
 1    HN                        object
 2    VN                        int64
 3    AN                        object
 4    Age                       object
 5    Sex                       object
 6    DateRecord                object
 7    TimeRecord                object
 8    ICUDateTime               object
 9    record_id                 float64
 10   redcap_event              object
 11   icu_kku                   float64
 12   h_adm_date                object
 13   icu_adm_date              object
 14   sex                       float64
 15   age                       float64
 16   time_to_icu               float64
 17   pdx                       float64
 18   reason_icu                float64
 19   insurance                 float64
 20   insurance_oth             object
 21   postcode                  float64
 22   weight                    float64
 23   height                    float64
 24   bmi                       float64
 25   pregnancy                 float64
 26   gestatiion_wk             float64
 27   ckd                       float64
 28   ckd_stage                 float64
 29   h_adm_source              float64
 30   icu_adm_source            float64
 31   elective_surg             float64
 32   arrest_bf                 float64
 33   cci___1                   float64
 34   cci___2                   float64
 35   cci___3                   float64
 36   cci___4                   float64
 37   cci___5                   float64
 38   cci___6                   float64
 39   cci___7                   float64
 40   cci___8                   float64
 41   cci___9                   float64
 42   cci___10                  float64
 43   cci___11                  float64
 44   cci___12                  float64
 45   cci___13                  float64
 46   cci___14                  float64
 47   cci___15                  float64
 48   cci___16                  float64
 49   cci___17                  float64
 50   cci___18                  float64
 51   cci___19                  float64
 52   cci___0                   float64
 53   cci_total                 float64
 54   lactate_24h               float64
 55   apache_3                  float64
 56   sofa                      float64
 57   sap_2                     float64
 58   mv_icu                    float64
 59   num_ettube                float64
 60   mv_start_1                object
 61   mv_end_1                  object
 62   mv_start_2                object
 63   mv_end_2                  object
 64   mv_start_3                object
 65   mv_end_3                  object
 66   mv_start_4                float64
 67   mv_end_4                  float64
 68   mv_duration               float64
 69   niv                       float64
 70   ecmo                      float64
 71   iabp                      float64
 72   hemoperfusion             float64
 73   shock                     float64
 74   shock_type___1            float64
 75   shock_type___2            float64
 76   shock_type___3            float64
 77   shock_type___4            float64
 78   shock_type___5            float64
 79   ino_vaso                  float64
 80   vaso_start_date           object
 81   vaso_stop_date            object
 82   shock_reversal_time       float64
 83   ttm                       float64
 84   plex                      float64
 85   pan_inf                   float64
 86   thrombolytic_ami          float64
 87   frailty                   float64
 88   delirium                  float64
 89   press_inj                 float64
 90   press_inj_stage           float64
 91   cumm_fluid                float64
 92   fluid_overload            float64
 93   aki                       float64
 94   aki_onset                 object
 95   aki_stage                 float64
 96   aki_date                  object
 97   time_icutoaki             float64
 98   aki_etio___1              float64
 99   aki_etio___2              float64
 100  aki_etio___3              float64
 101  aki_etio___4              float64
 102  aki_etio___5              float64
 103  aki_etio___6              float64
 104  aki_etio___7              float64
 105  aki_etio___8              float64
 106  aki_etio___9              float64
 107  aki_etio___10             float64
 108  aki_etio___11             float64
 109  aki_etio___12             float64
 110  fst                       float64
 111  fst_response              float64
 112  diuretic_bf               float64
 113  nephrolist_bf___1         float64
 114  nephrolist_bf___2         float64
 115  nephrolist_bf___3         float64
 116  nephrolist_bf___4         float64
 117  nephrolist_bf___5         float64
 118  nephrolist_bf___6         float64
 119  nephrolist_bf___7         float64
 120  nephrolist_bf___8         float64
 121  nephrolist_bf___9         float64
 122  nephrolist_bf___10        float64
 123  nephrolist_bf___0         float64
 124  nephrolist_af___1         float64
 125  nephrolist_af___2         float64
 126  nephrolist_af___3         float64
 127  nephrolist_af___4         float64
 128  nephrolist_af___5         float64
 129  nephrolist_af___6         float64
 130  nephrolist_af___7         float64
 131  nephrolist_af___8         float64
 132  nephrolist_af___9         float64
 133  nephrolist_af___10        float64
 134  nephrolist_af___0         float64
 135  rrt                       float64
 136  rrt_start                 object
 137  rrt_type___1              float64
 138  rrt_type___2              float64
 139  rrt_type___3              float64
 140  rrt_type___4              float64
 141  rfd_28                    float64
 142  icu_dc_dest               float64
 143  icu_los                   float64
 144  h_dc_dest                 float64
 145  h_los                     float64
 146  h_mort                    float64
 147  icu_mort                  float64
 148  mort_28                   float64
 149  surv_28                   float64
 150  mort_90                   float64
 151  surv_90                   float64
 152  vfd_28                    float64
 153  sfd_28                    float64
 154  cvs                       float64
 155  neuro                     float64
 156  cirrhosis                 float64
 157  dm                        float64
 158  cancer                    float64
 159  R_ID                      object
 160  DATA_TYPE                 object
 161  AdmissionID_snomed        float64
 162  VN_snomed                 float64
 163  conceptId                 float64
 164  ICD10_CODE                object
 165  definitionStatus          object
 166  term                      object
 167  term_long                 object
 168  USER_UPDATE               object
 169  CREATE_DATE               float64
 170  LAST_UPDATE               float64
 171  SNOMED_STATUS             object
 172  _merge                    object
 173  R_ID_io                   float64
 174  ICUDate                   object
 175  TotalIntake_Shift1        float64
 176  TotalIntake_Shift2        float64
 177  TotalIntake_Shift3        float64
 178  TotalIntake_24hr          float64
 179  TotalIntake_IV            float64
 180  TotalIntake_ORAL          float64
 181  TotalOuput_Shift1         float64
 182  TotalOuput_Shift2         float64
 183  TotalOuput_Shift3         float64
 184  TotalOuput_24hr           float64
 185  IO_Shift1                 float64
 186  IO_Shift2                 float64
 187  IO_Shift3                 float64
 188  IO_24hr                   float64
 189  LastUpdate                float64
 190  exist0                    object
 191  R_ID_bed                  float64
 192  HN_bed                    float64
 193  AN_bed                    float64
 194  ICUTime                   object
 195  HR                        float64
 196  BP_SYS                    float64
 197  BP_DIA                    float64
 198  BP_TYPE                   object
 199  MAP                       float64
 200  Temp                      float64
 201  RR                        float64
 202  O2SAT                     float64
 203  PPV                       float64
 204  CVP                       float64
 205  CO                        float64
 206  SETTING_ModeVentilator    object
 207  SETTING_RR                float64
 208  SETTING_RR_Mech           float64
 209  SETTING_FlowTrigger       float64
 210  SETTING_TidalVolume       float64
 211  SETTING_FIO2              float64
 212  SETTING_PeakFlow          float64
 213  SETTING_PEEP              float64
 214  SETTING_PSV               float64
 215  SETTING_InspTime          float64
 216  SETTING_InspPressure      float64
 217  SETTING_IE                float64
 218  SETTING_EndFlow           float64
 219  SETTING_BiasFlow          float64
 220  SETTING_PressureRiseTime  float64
 221  SETTING_PresTrigger       float64
 222  SETTING_PSVRiseTime       float64
 223  SETTING_Phigh             float64
 224  SETTING_Plow              float64
 225  SETTING_Thigh             float64
 226  SETTING_Tlow              float64
 227  SETTING_Tsupp             float64
 228  LIVE_RR                   float64
 229  LIVE_TidalVolume          float64
 230  LIVE_PIP                  float64
 231  LIVE_DynamaicPEEPe        float64
 232  LIVE_PMEAN                float64
 233  LIVE_Pplat                float64
 234  LIVE_MV                   float64
 235  LIVE_FIO2                 float64
 236  LIVE_MV_spont             float64
 237  LIVE_TidalVolume_spont    float64
 238  LIVE_RR_spont             float64
 239  LIVE_RSBI                 float64
 240  LIVE_MV_Mech              float64
 241  LIVE_TidalVolume_Mech     float64
 242  LIVE_DynamicCompliance    float64
 243  LIVE_Raw                  float64
 244  LIVE_StaticCompliance     float64
 245  LIVE_StaticPplat          float64
 246  LIVE_StaticPEEPe          float64
 247  LIVE_StaticPEEPi          float64
 248  LIVE_PEEPe_PEEPi          float64
 249  LIVE_EE                   float64
 250  LIVE_RQ                   float64
 251  LIVE_VO2                  float64
 252  LIVE_VCO2                 float64
 253  LIVE_VO2_M2               float64
 254  LIVE_VCO2_M2              float64
 255  OUTPUT_01                 float64
 256  OUTPUT_01_DETAIL          object
 257  OUTPUT_02                 float64
 258  OUTPUT_02_DETAIL          object
 259  OUTPUT_03                 float64
 260  OUTPUT_03_DETAIL          object
 261  OUTPUT_04                 float64
 262  OUTPUT_04_DETAIL          float64
 263  OUTPUT_05                 float64
 264  OUTPUT_05_DETAIL          float64
 265  OUTPUT_06                 float64
 266  OUTPUT_06_DETAIL          float64
 267  OUTPUT_07                 float64
 268  OUTPUT_07_DETAIL          float64
 269  OUTPUT_08                 float64
 270  OUTPUT_08_DETAIL          float64
 271  ABG_PH                    float64
 272  ABG_PCO2                  float64
 273  ABG_TCO2                  float64
 274  ABG_PO2                   float64
 275  ABG_FIO2                  float64
 276  ABG_BE                    float64
 277  ABG_HCO3                  float64
 278  ABG_O2SAT                 float64
 279  BICHEM_BS                 float64
 280  BICHEM_DTX                float64
 281  BICHEM_BUN                float64
 282  BICHEM_CR                 float64
 283  BICHEM_NA                 float64
 284  BICHEM_K                  float64
 285  BICHEM_HCO3               float64
 286  BICHEM_CL                 float64
 287  BICHEM_CA                 float64
 288  BICHEM_PO4                float64
 289  BICHEM_MG                 float64
 290  BICHEM_ALB                float64
 291  BICHEM_LACTATE            float64
 292  ICUDateTime_bed           object
 293  exist1                    object
 294  R_ID_lab                  float64
 295  ICUDate_lab               object
 296  ICUTime_lab               object
 297  ABG_PH_lab                float64
 298  ABG_PCO2_lab              float64
 299  ABG_TCO2_lab              float64
 300  ABG_PO2_lab               float64
 301  ABG_FIO2_lab              float64
 302  ABG_BE_lab                float64
 303  ABG_HCO3_lab              float64
 304  ABG_O2SAT_lab             float64
 305  BICHEM_BS_lab             float64
 306  BICHEM_DTX_lab            float64
 307  BICHEM_BUN_lab            float64
 308  BICHEM_CR_lab             float64
 309  BICHEM_NA_lab             float64
 310  BICHEM_K_lab              float64
 311  BICHEM_HCO3_lab           float64
 312  BICHEM_CL_lab             float64
 313  BICHEM_CA_lab             float64
 314  BICHEM_PO4_lab            float64
 315  BICHEM_MG_lab             float64
 316  BICHEM_ALB_lab            float64
 317  BICHEM_LACTATE_lab        float64
 318  LAST_UPDATE_lab           float64
 319  exist2                    object
 320  R_ID_monitor              float64
 321  BedID                     object
 322  ICUDate_monitor           object
 323  ICUTime_monitor           object
 324  HR_monitor                float64
 325  RR_monitor                float64
 326  BP_SYS_monitor            float64
 327  BP_DIA_monitor            float64
 328  BP_TYPE_monitor           object
 329  MAP_monitor               float64
 330  Temp_monitor              float64
 331  O2SAT_monitor             float64
 332  PPV_monitor               float64
 333  CVP_monitor               float64
 334  LastUpdate_monitor        float64
 335  exist3                    object
dtypes: float64(285), int64(2), object(49)
memory usage: 22.2+ MB

<ipython-input-48-531af5cb9dcf>:1: DtypeWarning: Columns (65,66,199,207,257,259,261,296,297,322,323,324,329) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(path+"table_276.csv")

In [10]:
data

,AdmissionID,HN,VN,AN,Age,Sex,DateRecord,TimeRecord,ICUDateTime,record_id,...,BP_SYS_monitor,BP_DIA_monitor,BP_TYPE_monitor,MAP_monitor,Temp_monitor,O2SAT_monitor,PPV_monitor,CVP_monitor,LastUpdate_monitor,exist3
0,1682584169677,HX7301,10305834,I23-003652,61 ปี,ชาย,2023-04-27,1900-01-01 15:29:00,2023-04-27 15:29:00,425.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,1682584169677,HX7301,10305834,I23-003652,61 ปี,ชาย,2023-04-27,1900-01-01 15:29:00,2023-04-27 15:29:00,425.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,1682584169677,HX7301,10305834,I23-003652,61 ปี,ชาย,2023-04-27,1900-01-01 15:29:00,2023-04-27 15:29:00,425.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,1682584169677,HX7301,10305834,I23-003652,61 ปี,ชาย,2023-04-27,1900-01-01 15:29:00,2023-04-27 15:29:00,425.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,1682584169677,HX7301,10305834,I23-003652,61 ปี,ชาย,2023-04-27,1900-01-01 15:29:00,2023-04-27 15:29:00,425.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8660,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,1900-01-01 18:42:00,2023-12-31 18:42:00,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8661,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,1900-01-01 18:42:00,2023-12-31 18:42:00,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8662,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,1900-01-01 18:42:00,2023-12-31 18:42:00,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8663,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,1900-01-01 18:42:00,2023-12-31 18:42:00,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8664,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,1900-01-01 18:42:00,2023-12-31 18:42:00,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [11]:
data['AdmissionID'].nunique()

276

In [29]:
data_1 = data.copy()

In [45]:
# Drop Nan > 40%
# Calculate percentage of NaN values for each column
nan_percentages = data.isnull().mean(axis=0) * 100
# Threshold for dropping columns
threshold = 100
# Get columns to drop (where NaN percentage is above threshold)
columns_to_drop = nan_percentages[nan_percentages >= threshold].index.tolist()
data.drop(columns_to_drop, axis=1, inplace=True)

In [46]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8665 entries, 0 to 8664
Data columns (total 229 columns):
 #    Column                    Dtype
---   ------                    -----
 0    AdmissionID               int64
 1    HN                        object
 2    VN                        int64
 3    AN                        object
 4    Age                       object
 5    Sex                       object
 6    DateRecord                object
 7    TimeRecord                object
 8    ICUDateTime               object
 9    record_id                 float64
 10   redcap_event              object
 11   icu_kku                   float64
 12   h_adm_date                object
 13   icu_adm_date              object
 14   sex                       float64
 15   age                       float64
 16   time_to_icu               float64
 17   pdx                       float64
 18   reason_icu                float64
 19   insurance                 float64
 20   postcode                  float64
 21   weight                    float64
 22   height                    float64
 23   bmi                       float64
 24   pregnancy                 float64
 25   ckd                       float64
 26   ckd_stage                 float64
 27   h_adm_source              float64
 28   icu_adm_source            float64
 29   elective_surg             float64
 30   arrest_bf                 float64
 31   cci___1                   float64
 32   cci___2                   float64
 33   cci___3                   float64
 34   cci___4                   float64
 35   cci___5                   float64
 36   cci___6                   float64
 37   cci___7                   float64
 38   cci___8                   float64
 39   cci___9                   float64
 40   cci___10                  float64
 41   cci___11                  float64
 42   cci___12                  float64
 43   cci___13                  float64
 44   cci___14                  float64
 45   cci___15                  float64
 46   cci___16                  float64
 47   cci___17                  float64
 48   cci___18                  float64
 49   cci___19                  float64
 50   cci___0                   float64
 51   cci_total                 float64
 52   lactate_24h               float64
 53   apache_3                  float64
 54   sofa                      float64
 55   sap_2                     float64
 56   mv_icu                    float64
 57   num_ettube                float64
 58   mv_start_1                object
 59   mv_end_1                  object
 60   mv_start_2                object
 61   mv_end_2                  object
 62   mv_duration               float64
 63   niv                       float64
 64   ecmo                      float64
 65   iabp                      float64
 66   hemoperfusion             float64
 67   shock                     float64
 68   shock_type___1            float64
 69   shock_type___2            float64
 70   shock_type___3            float64
 71   shock_type___4            float64
 72   shock_type___5            float64
 73   ino_vaso                  float64
 74   vaso_start_date           object
 75   vaso_stop_date            object
 76   shock_reversal_time       float64
 77   ttm                       float64
 78   plex                      float64
 79   pan_inf                   float64
 80   thrombolytic_ami          float64
 81   frailty                   float64
 82   delirium                  float64
 83   press_inj                 float64
 84   aki                       float64
 85   aki_onset                 object
 86   aki_stage                 float64
 87   aki_date                  object
 88   time_icutoaki             float64
 89   aki_etio___1              float64
 90   aki_etio___2              float64
 91   aki_etio___3              float64
 92   aki_etio___4              float64
 93   aki_etio___5              float64
 94   aki_etio___6              float64
 95   aki_etio___7              float64
 96   aki_etio___8              float64
 97   aki_etio___9              float64
 98   aki_etio___10             float64
 99   aki_etio___11             float64
 100  aki_etio___12             float64
 101  fst                       float64
 102  fst_response              float64
 103  diuretic_bf               float64
 104  nephrolist_bf___1         float64
 105  nephrolist_bf___2         float64
 106  nephrolist_bf___3         float64
 107  nephrolist_bf___4         float64
 108  nephrolist_bf___5         float64
 109  nephrolist_bf___6         float64
 110  nephrolist_bf___7         float64
 111  nephrolist_bf___8         float64
 112  nephrolist_bf___9         float64
 113  nephrolist_bf___10        float64
 114  nephrolist_bf___0         float64
 115  nephrolist_af___1         float64
 116  nephrolist_af___2         float64
 117  nephrolist_af___3         float64
 118  nephrolist_af___4         float64
 119  nephrolist_af___5         float64
 120  nephrolist_af___6         float64
 121  nephrolist_af___7         float64
 122  nephrolist_af___8         float64
 123  nephrolist_af___9         float64
 124  nephrolist_af___10        float64
 125  nephrolist_af___0         float64
 126  rrt                       float64
 127  rrt_start                 object
 128  rrt_type___1              float64
 129  rrt_type___2              float64
 130  rrt_type___3              float64
 131  rrt_type___4              float64
 132  rfd_28                    float64
 133  icu_dc_dest               float64
 134  icu_los                   float64
 135  h_dc_dest                 float64
 136  h_los                     float64
 137  h_mort                    float64
 138  icu_mort                  float64
 139  mort_28                   float64
 140  surv_28                   float64
 141  mort_90                   float64
 142  surv_90                   float64
 143  vfd_28                    float64
 144  sfd_28                    float64
 145  cvs                       float64
 146  neuro                     float64
 147  cirrhosis                 float64
 148  dm                        float64
 149  cancer                    float64
 150  R_ID                      object
 151  DATA_TYPE                 object
 152  AdmissionID_snomed        float64
 153  VN_snomed                 float64
 154  conceptId                 float64
 155  ICD10_CODE                object
 156  definitionStatus          object
 157  term                      object
 158  term_long                 object
 159  USER_UPDATE               object
 160  CREATE_DATE               float64
 161  LAST_UPDATE               float64
 162  SNOMED_STATUS             object
 163  _merge                    object
 164  R_ID_io                   float64
 165  ICUDate                   object
 166  TotalIntake_Shift1        float64
 167  TotalIntake_Shift2        float64
 168  TotalIntake_Shift3        float64
 169  TotalIntake_24hr          float64
 170  TotalIntake_IV            float64
 171  TotalIntake_ORAL          float64
 172  TotalOuput_Shift1         float64
 173  TotalOuput_Shift2         float64
 174  TotalOuput_Shift3         float64
 175  TotalOuput_24hr           float64
 176  IO_Shift1                 float64
 177  IO_Shift2                 float64
 178  IO_Shift3                 float64
 179  IO_24hr                   float64
 180  LastUpdate                float64
 181  exist0                    object
 182  R_ID_bed                  float64
 183  ICUTime                   object
 184  HR                        float64
 185  BP_TYPE                   object
 186  Temp                      float64
 187  O2SAT                     float64
 188  SETTING_ModeVentilator    object
 189  SETTING_RR                float64
 190  SETTING_FlowTrigger       float64
 191  SETTING_FIO2              float64
 192  SETTING_PEEP              float64
 193  SETTING_InspTime          float64
 194  SETTING_InspPressure      float64
 195  SETTING_BiasFlow          float64
 196  SETTING_PressureRiseTime  float64
 197  LIVE_RR                   float64
 198  LIVE_TidalVolume          float64
 199  LIVE_PIP                  float64
 200  LIVE_DynamaicPEEPe        float64
 201  LIVE_PMEAN                float64
 202  LIVE_MV                   float64
 203  LIVE_FIO2                 float64
 204  LIVE_MV_spont             float64
 205  LIVE_RR_spont             float64
 206  LIVE_MV_Mech              float64
 207  LIVE_TidalVolume_Mech     float64
 208  LIVE_DynamicCompliance    float64
 209  LIVE_Raw                  float64
 210  LIVE_StaticCompliance     float64
 211  OUTPUT_01                 float64
 212  OUTPUT_01_DETAIL          object
 213  ICUDateTime_bed           object
 214  exist1                    object
 215  exist2                    object
 216  R_ID_monitor              float64
 217  BedID                     object
 218  ICUDate_monitor           object
 219  ICUTime_monitor           object
 220  HR_monitor                float64
 221  RR_monitor                float64
 222  BP_SYS_monitor            float64
 223  BP_DIA_monitor            float64
 224  BP_TYPE_monitor           object
 225  MAP_monitor               float64
 226  O2SAT_monitor             float64
 227  LastUpdate_monitor        float64
 228  exist3                    object
dtypes: float64(185), int64(2), object(42)
memory usage: 15.1+ MB

In [50]:
data[['BP_SYS']][~data['BP_SYS'].isna()]

      BP_SYS
4300   152.0
4302   152.0
4304   152.0
4306   152.0
4308   152.0
...      ...
5372   167.0
5373    72.0
5374    93.0
5375   171.0
5376   167.0

[622 rows x 1 columns]

In [51]:
data[['MAP']][~data['MAP'].isna()]

        MAP
4300  105.0
4302  105.0
4304  105.0
4306  105.0
4308  105.0
...     ...
5372  109.0
5373   49.0
5374   74.0
5375  116.0
5376  109.0

[622 rows x 1 columns]

In [54]:
shock = data[(data['MAP']<65)|(data['BP_SYS']<90)]
shock

,AdmissionID,HN,VN,AN,Age,Sex,DateRecord,TimeRecord,ICUDateTime,record_id,...,BP_SYS_monitor,BP_DIA_monitor,BP_TYPE_monitor,MAP_monitor,Temp_monitor,O2SAT_monitor,PPV_monitor,CVP_monitor,LastUpdate_monitor,exist3
4793,1699100363630,KX2849,11341393,I23-042751,50 ปี,หญิง,2023-11-04,1900-01-01 19:19:00,2023-11-04 19:19:00,802.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4798,1699100363630,KX2849,11341393,I23-042751,50 ปี,หญิง,2023-11-04,1900-01-01 19:19:00,2023-11-04 19:19:00,802.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4803,1699100363630,KX2849,11341393,I23-042751,50 ปี,หญิง,2023-11-04,1900-01-01 19:19:00,2023-11-04 19:19:00,802.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4808,1699100363630,KX2849,11341393,I23-042751,50 ปี,หญิง,2023-11-04,1900-01-01 19:19:00,2023-11-04 19:19:00,802.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4813,1699100363630,KX2849,11341393,I23-042751,50 ปี,หญิง,2023-11-04,1900-01-01 19:19:00,2023-11-04 19:19:00,802.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5357,1700050182171,IP5735,11310797,I23-041600,61 ปี,ชาย,2023-11-15,1900-01-01 19:09:00,2023-11-15 19:09:00,842.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5361,1700050182171,IP5735,11310797,I23-041600,61 ปี,ชาย,2023-11-15,1900-01-01 19:09:00,2023-11-15 19:09:00,842.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5365,1700050182171,IP5735,11310797,I23-041600,61 ปี,ชาย,2023-11-15,1900-01-01 19:09:00,2023-11-15 19:09:00,842.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5369,1700050182171,IP5735,11310797,I23-041600,61 ปี,ชาย,2023-11-15,1900-01-01 19:09:00,2023-11-15 19:09:00,842.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5373,1700050182171,IP5735,11310797,I23-041600,61 ปี,ชาย,2023-11-15,1900-01-01 19:09:00,2023-11-15 19:09:00,842.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [55]:
#จะได้ว่า ช็อกทั้งหมด 3 คน
shock['AdmissionID'].nunique()

3