<a href="https://colab.research.google.com/github/Tonry12/Data_joyx2/blob/main/Laos_lotto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
lotto = pd.read_csv('/content/drive/MyDrive/SPN/Laos_Lotto.csv')

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy
import os
import pickle
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
lotto

          date  เลข 4 ตัว  เลข 3 ตัว  เลข 2 ตัว  weekday_dum    weekday
0     5/3/2024       7999        999         99            6     Friday
1    4/29/2024       4351        351         51            2     Monday
2    4/26/2024       8721        721         21            6     Friday
3    4/24/2024       2552        552         52            4  Wednesday
4    4/22/2024       9490        490         90            2     Monday
..         ...        ...        ...        ...          ...        ...
144  5/19/2023       8573        573         73            6     Friday
145  5/17/2023       9846        846         46            4  Wednesday
146  5/15/2023       8649        649         49            2     Monday
147  5/12/2023       4077         77         77            6     Friday
148  5/10/2023       8521        521         21            4  Wednesday

[149 rows x 6 columns]

In [5]:
lotto.isnull().any()

date           False
เลข 4 ตัว      False
เลข 3 ตัว      False
เลข 2 ตัว      False
weekday_dum    False
weekday        False
dtype: bool

In [6]:
lotto.rename(columns={'เลข 4 ตัว': 'top4','เลข 3 ตัว':'top3','เลข 2 ตัว':'top2'},inplace=True)

In [7]:
lt = lotto.drop(columns=['weekday_dum'])

In [8]:
lt['date'] = pd.to_datetime(lt['date'])

In [9]:
lt.dtypes

date       datetime64[ns]
top4                int64
top3                int64
top2                int64
weekday            object
dtype: object

In [10]:
lt['top4'] = lt['top4'].apply(lambda x: '{:04}'.format(x))

In [11]:
lt

          date  top4  top3  top2    weekday
0   2024-05-03  7999   999    99     Friday
1   2024-04-29  4351   351    51     Monday
2   2024-04-26  8721   721    21     Friday
3   2024-04-24  2552   552    52  Wednesday
4   2024-04-22  9490   490    90     Monday
..         ...   ...   ...   ...        ...
144 2023-05-19  8573   573    73     Friday
145 2023-05-17  9846   846    46  Wednesday
146 2023-05-15  8649   649    49     Monday
147 2023-05-12  4077    77    77     Friday
148 2023-05-10  8521   521    21  Wednesday

[149 rows x 5 columns]

In [12]:
lt_1 = lt

In [13]:
lt_1['top4'] = lt_1['top4'].astype(str)

# Split each value in the 'digi' column into its individual digits
lt_1['r1'] = lt_1['top4'].apply(lambda x: int(x[0]))
lt_1['r2'] = lt_1['top4'].apply(lambda x: int(x[1]))
lt_1['r3'] = lt_1['top4'].apply(lambda x: int(x[2]))
lt_1['r4'] = lt_1['top4'].apply(lambda x: int(x[3]))

In [14]:
lt_1= lt_1.drop(columns=['top3','top2'])

In [15]:
lt_1

          date  top4    weekday  r1  r2  r3  r4
0   2024-05-03  7999     Friday   7   9   9   9
1   2024-04-29  4351     Monday   4   3   5   1
2   2024-04-26  8721     Friday   8   7   2   1
3   2024-04-24  2552  Wednesday   2   5   5   2
4   2024-04-22  9490     Monday   9   4   9   0
..         ...   ...        ...  ..  ..  ..  ..
144 2023-05-19  8573     Friday   8   5   7   3
145 2023-05-17  9846  Wednesday   9   8   4   6
146 2023-05-15  8649     Monday   8   6   4   9
147 2023-05-12  4077     Friday   4   0   7   7
148 2023-05-10  8521  Wednesday   8   5   2   1

[149 rows x 7 columns]

# วันจันทร์

## เลขท้าย 4 ตัว

In [16]:
monday = lt_1[lt_1['weekday'] == "Monday"]

In [17]:
monday.head()

         date  top4 weekday  r1  r2  r3  r4
1  2024-04-29  4351  Monday   4   3   5   1
4  2024-04-22  9490  Monday   9   4   9   0
8  2024-04-08  9545  Monday   9   5   4   5
11 2024-04-01  1596  Monday   1   5   9   6
16 2024-03-18  8302  Monday   8   3   0   2

In [18]:
# เลขท้ายสี่ตัวหลักที่ 1 ที่ออกบ่อยสุด
grouped_counts = monday.groupby('r1').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r1  Count
9   9     10

In [19]:
# เลขท้ายสี่ตัวหลักที่ 2 ที่ออกบ่อยสุด
grouped_counts = monday.groupby('r2').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r2  Count
8   8      9

In [20]:
# เลขท้ายสี่ตัวหลักที่ 3 ที่ออกบ่อยสุด
grouped_counts = monday.groupby('r3').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r3  Count
2   2      8
9   9      8

In [21]:
# เลขท้ายสี่ตัวหลักที่ 4 ที่ออกบ่อยสุด
grouped_counts = monday.groupby('r4').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r4  Count
5   5      8

### สรุป เลขท้าย 4 ตัวที่ออกบ่อยที่สุดคือ 9825 หรือ 9895

# งวดวันพุธ

In [22]:
wed = lt_1[lt_1['weekday'] == "Wednesday"]

In [23]:
wed

          date  top4    weekday  r1  r2  r3  r4
3   2024-04-24  2552  Wednesday   2   5   5   2
7   2024-04-10  4389  Wednesday   4   3   8   9
10  2024-04-03  1959  Wednesday   1   9   5   9
13  2024-03-27  0911  Wednesday   0   9   1   1
15  2024-03-20  7706  Wednesday   7   7   0   6
18  2024-03-13  1857  Wednesday   1   8   5   7
20  2024-03-06  6478  Wednesday   6   4   7   8
23  2024-02-28  6118  Wednesday   6   1   1   8
26  2024-02-21  3890  Wednesday   3   8   9   0
29  2024-02-14  7243  Wednesday   7   2   4   3
32  2024-02-07  8368  Wednesday   8   3   6   8
35  2024-01-31  8932  Wednesday   8   9   3   2
38  2024-01-24  7380  Wednesday   7   3   8   0
41  2024-01-17  1226  Wednesday   1   2   2   6
44  2024-01-10  8391  Wednesday   8   3   9   1
47  2024-01-03  3873  Wednesday   3   8   7   3
49  2023-12-27  8785  Wednesday   8   7   8   5
52  2023-12-20  9922  Wednesday   9   9   2   2
55  2023-12-13  2232  Wednesday   2   2   3   2
58  2023-12-06  4186  Wednesday   4   1   8   6
61  2023-11-29  5288  Wednesday   5   2   8   8
64  2023-11-22  4264  Wednesday   4   2   6   4
67  2023-11-15  5514  Wednesday   5   5   1   4
70  2023-11-08  7939  Wednesday   7   9   3   9
73  2023-11-01  5402  Wednesday   5   4   0   2
76  2023-10-25  0480  Wednesday   0   4   8   0
79  2023-10-18  6273  Wednesday   6   2   7   3
82  2023-10-11  9264  Wednesday   9   2   6   4
85  2023-10-04  9629  Wednesday   9   6   2   9
88  2023-09-27  0210  Wednesday   0   2   1   0
91  2023-09-20  7372  Wednesday   7   3   7   2
94  2023-09-13  8831  Wednesday   8   8   3   1
97  2023-09-06  1717  Wednesday   1   7   1   7
100 2023-08-30  2529  Wednesday   2   5   2   9
103 2023-08-23  3061  Wednesday   3   0   6   1
106 2023-08-16  1697  Wednesday   1   6   9   7
109 2023-08-09  3116  Wednesday   3   1   1   6
112 2023-08-02  7809  Wednesday   7   8   0   9
115 2023-07-26  1350  Wednesday   1   3   5   0
118 2023-07-19  5878  Wednesday   5   8   7   8
121 2023-07-12  1034  Wednesday   1   0   3   4
124 2023-07-05  0908  Wednesday   0   9   0   8
127 2023-06-28  2229  Wednesday   2   2   2   9
130 2023-06-21  7341  Wednesday   7   3   4   1
133 2023-06-14  2952  Wednesday   2   9   5   2
136 2023-06-07  0318  Wednesday   0   3   1   8
139 2023-05-31  7922  Wednesday   7   9   2   2
142 2023-05-24  2572  Wednesday   2   5   7   2
145 2023-05-17  9846  Wednesday   9   8   4   6
148 2023-05-10  8521  Wednesday   8   5   2   1

In [24]:
# เลขท้ายสี่ตัวหลักที่ 1 ที่ออกบ่อยสุด
grouped_counts = wed.groupby('r1').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r1  Count
7   7      8

In [25]:
# เลขท้ายสี่ตัวหลักที่ 2 ที่ออกบ่อยสุด
grouped_counts = wed.groupby('r2').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r2  Count
2   2      9

In [32]:
# เลขท้ายสี่ตัวหลักที่ 3 ที่ออกบ่อยสุด
grouped_counts = wed.groupby('r3').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r3  Count
1   1      7
2   2      7

In [27]:
# เลขท้ายสี่ตัวหลักที่ 4 ที่ออกบ่อยสุด
grouped_counts = wed.groupby('r4').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

   r4  Count
2   2      9

### สรุป เลขท้าย 4 ตัวที่ออกบ่อยที่สุดคือ 7212 หรือ 7222

In [28]:
wed_1 = lt[lt['weekday'] == "Wednesday"]

In [29]:
wed_1

          date  top4  top3  top2    weekday  r1  r2  r3  r4
3   2024-04-24  2552   552    52  Wednesday   2   5   5   2
7   2024-04-10  4389   389    89  Wednesday   4   3   8   9
10  2024-04-03  1959   959    59  Wednesday   1   9   5   9
13  2024-03-27  0911   911    11  Wednesday   0   9   1   1
15  2024-03-20  7706   706     6  Wednesday   7   7   0   6
18  2024-03-13  1857   857    57  Wednesday   1   8   5   7
20  2024-03-06  6478   478    78  Wednesday   6   4   7   8
23  2024-02-28  6118   118    18  Wednesday   6   1   1   8
26  2024-02-21  3890   890    90  Wednesday   3   8   9   0
29  2024-02-14  7243   243    43  Wednesday   7   2   4   3
32  2024-02-07  8368   368    68  Wednesday   8   3   6   8
35  2024-01-31  8932   932    32  Wednesday   8   9   3   2
38  2024-01-24  7380   380    80  Wednesday   7   3   8   0
41  2024-01-17  1226   226    26  Wednesday   1   2   2   6
44  2024-01-10  8391   391    91  Wednesday   8   3   9   1
47  2024-01-03  3873   873    73  Wednesday   3   8   7   3
49  2023-12-27  8785   785    85  Wednesday   8   7   8   5
52  2023-12-20  9922   922    22  Wednesday   9   9   2   2
55  2023-12-13  2232   232    32  Wednesday   2   2   3   2
58  2023-12-06  4186   186    86  Wednesday   4   1   8   6
61  2023-11-29  5288   288    88  Wednesday   5   2   8   8
64  2023-11-22  4264   264    64  Wednesday   4   2   6   4
67  2023-11-15  5514   514    14  Wednesday   5   5   1   4
70  2023-11-08  7939   939    39  Wednesday   7   9   3   9
73  2023-11-01  5402   402     2  Wednesday   5   4   0   2
76  2023-10-25  0480   480    80  Wednesday   0   4   8   0
79  2023-10-18  6273   273    73  Wednesday   6   2   7   3
82  2023-10-11  9264   264    64  Wednesday   9   2   6   4
85  2023-10-04  9629   629    29  Wednesday   9   6   2   9
88  2023-09-27  0210   210    10  Wednesday   0   2   1   0
91  2023-09-20  7372   372    72  Wednesday   7   3   7   2
94  2023-09-13  8831   831    31  Wednesday   8   8   3   1
97  2023-09-06  1717   717    17  Wednesday   1   7   1   7
100 2023-08-30  2529   529    29  Wednesday   2   5   2   9
103 2023-08-23  3061    61    61  Wednesday   3   0   6   1
106 2023-08-16  1697   697    97  Wednesday   1   6   9   7
109 2023-08-09  3116   116    16  Wednesday   3   1   1   6
112 2023-08-02  7809   809     9  Wednesday   7   8   0   9
115 2023-07-26  1350   350    50  Wednesday   1   3   5   0
118 2023-07-19  5878   878    78  Wednesday   5   8   7   8
121 2023-07-12  1034    34    34  Wednesday   1   0   3   4
124 2023-07-05  0908   908     8  Wednesday   0   9   0   8
127 2023-06-28  2229   229    29  Wednesday   2   2   2   9
130 2023-06-21  7341   341    41  Wednesday   7   3   4   1
133 2023-06-14  2952   952    52  Wednesday   2   9   5   2
136 2023-06-07  0318   318    18  Wednesday   0   3   1   8
139 2023-05-31  7922   922    22  Wednesday   7   9   2   2
142 2023-05-24  2572   572    72  Wednesday   2   5   7   2
145 2023-05-17  9846   846    46  Wednesday   9   8   4   6
148 2023-05-10  8521   521    21  Wednesday   8   5   2   1

In [34]:
grouped_counts

    top2  Count
0      2      1
1      6      1
2      8      1
3      9      1
4     10      1
5     11      1
6     14      1
7     16      1
8     17      1
9     18      2
10    21      1
11    22      2
12    26      1
13    29      3
14    31      1
15    32      2
16    34      1
17    39      1
18    41      1
19    43      1
20    46      1
21    50      1
22    52      2
23    57      1
24    59      1
25    61      1
26    64      2
27    68      1
28    72      2
29    73      2
30    78      2
31    80      2
32    85      1
33    86      1
34    88      1
35    89      1
36    90      1
37    91      1
38    97      1

In [33]:
# เลขท้าย2ตัวที่ออกบ่อยสุด
grouped_counts = wed_1.groupby('top2').size().reset_index(name='Count')
max_count_row = grouped_counts[grouped_counts['Count'] == grouped_counts['Count'].max()]
max_count_row

    top2  Count
13    29      3