<a href="https://colab.research.google.com/github/Tonry12/Data_joyx2/blob/main/mergeSmart_ICU_tonnaw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Read Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/MyDrive/smarticu_data/"

Mounted at /content/drive

In [3]:
# path = "data/"

### admission

In [4]:
admission = pd.read_csv(path+"icu_admission.csv")
admission = admission.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
admission.drop(['Unnamed: 0'], axis=1, inplace=True)
admission.VN = admission.VN.astype('Int64')
admission.AdmissionID = admission.AdmissionID.astype('Int64')
admission.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570 entries, 0 to 569
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AdmissionID  570 non-null    Int64
 1   HN           570 non-null    object
 2   VN           570 non-null    Int64
 3   AN           570 non-null    object
 4   Age          570 non-null    object
 5   Sex          570 non-null    object
 6   DateRecord   570 non-null    object
 7   TimeRecord   570 non-null    object
dtypes: Int64(2), object(6)
memory usage: 36.9+ KB

In [5]:
admission

,AdmissionID,HN,VN,AN,Age,Sex,DateRecord,TimeRecord
0,1669892759015,JR8123,10116794,I22-047074,66 ปี,ชาย,2022-12-01,18:05
1,1669968929608,BW3848,9945849,I22-040013,74 ปี,หญิง,2022-12-02,15:15
2,1669986847225,DN2086,10119971,I22-047178,82 ปี,หญิง,2022-12-02,20:14
3,1669987593264,CC7538,10120136,I22-047181,85 ปี,หญิง,2022-12-02,20:26
4,1670066559142,FW0443,10122372,I22-047245,42 ปี,ชาย,2022-12-03,18:22
...,...,...,...,...,...,...,...,...
565,1703773563260,HT8560,11510841,I23-049107,67 ปี,หญิง,2023-12-28,21:26
566,1703928233713,KY1203,11546116,I23-050381,30 ปี,หญิง,2023-12-30,16:23
567,1703957213084,EY9650,11546246,I23-050403,65 ปี,หญิง,2023-12-30,00:26
568,1703972587046,GO3388,11546237,I23-050413,76 ปี,หญิง,2023-12-30,04:43
569,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,18:42

In [6]:
print(admission['HN'].nunique(), admission['AN'].nunique())

507 542

In [7]:
admission.sort_values(by=['DateRecord','TimeRecord'], ascending=True, inplace=True)
admission = admission.drop_duplicates(subset=['HN'], keep='first')

In [8]:
print(admission['HN'].nunique(), admission['AN'].nunique())

507 507

In [9]:
admission

,AdmissionID,HN,VN,AN,Age,Sex,DateRecord,TimeRecord
0,1669892759015,JR8123,10116794,I22-047074,66 ปี,ชาย,2022-12-01,18:05
1,1669968929608,BW3848,9945849,I22-040013,74 ปี,หญิง,2022-12-02,15:15
2,1669986847225,DN2086,10119971,I22-047178,82 ปี,หญิง,2022-12-02,20:14
3,1669987593264,CC7538,10120136,I22-047181,85 ปี,หญิง,2022-12-02,20:26
4,1670066559142,FW0443,10122372,I22-047245,42 ปี,ชาย,2022-12-03,18:22
...,...,...,...,...,...,...,...,...
565,1703773563260,HT8560,11510841,I23-049107,67 ปี,หญิง,2023-12-28,21:26
567,1703957213084,EY9650,11546246,I23-050403,65 ปี,หญิง,2023-12-30,00:26
568,1703972587046,GO3388,11546237,I23-050413,76 ปี,หญิง,2023-12-30,04:43
566,1703928233713,KY1203,11546116,I23-050381,30 ปี,หญิง,2023-12-30,16:23
569,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,18:42

### bedccr

In [10]:
bedccr = pd.read_csv(path+"icu_bedccr.csv")
bedccr = bedccr.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
bedccr.drop(['Unnamed: 0'], axis=1, inplace=True)
bedccr.AdmissionID = bedccr.AdmissionID.astype('Int64')

bedccr.info(verbose=True)

<ipython-input-10-d4a2cf8e46b5>:1: DtypeWarning: Columns (8,9,11,12,13,14,15,16,17,72) have mixed types. Specify dtype option on import or set low_memory=False.
  bedccr = pd.read_csv(path+"icu_bedccr.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118939 entries, 0 to 118938
Data columns (total 103 columns):
 #    Column                    Dtype
---   ------                    -----
 0    R_ID                      int64
 1    AdmissionID               Int64
 2    HN                        float64
 3    AN                        float64
 4    ICUDate                   object
 5    ICUTime                   int64
 6    HR                        float64
 7    BP_SYS                    object
 8    BP_DIA                    object
 9    BP_TYPE                   object
 10   MAP                       object
 11   Temp                      object
 12   RR                        object
 13   O2SAT                     object
 14   PPV                       object
 15   CVP                       object
 16   CO                        object
 17   SETTING_ModeVentilator    object
 18   SETTING_RR                float64
 19   SETTING_RR_Mech           float64
 20   SETTING_FlowTrigger       float64
 21   SETTING_TidalVolume       float64
 22   SETTING_FIO2              float64
 23   SETTING_PeakFlow          float64
 24   SETTING_PEEP              float64
 25   SETTING_PSV               float64
 26   SETTING_InspTime          float64
 27   SETTING_InspPressure      float64
 28   SETTING_IE                float64
 29   SETTING_EndFlow           float64
 30   SETTING_BiasFlow          float64
 31   SETTING_PressureRiseTime  float64
 32   SETTING_PresTrigger       float64
 33   SETTING_PSVRiseTime       float64
 34   SETTING_Phigh             float64
 35   SETTING_Plow              float64
 36   SETTING_Thigh             float64
 37   SETTING_Tlow              float64
 38   SETTING_Tsupp             float64
 39   LIVE_RR                   float64
 40   LIVE_TidalVolume          float64
 41   LIVE_PIP                  float64
 42   LIVE_DynamaicPEEPe        float64
 43   LIVE_PMEAN                float64
 44   LIVE_Pplat                float64
 45   LIVE_MV                   float64
 46   LIVE_FIO2                 float64
 47   LIVE_MV_spont             float64
 48   LIVE_TidalVolume_spont    float64
 49   LIVE_RR_spont             float64
 50   LIVE_RSBI                 float64
 51   LIVE_MV_Mech              float64
 52   LIVE_TidalVolume_Mech     float64
 53   LIVE_DynamicCompliance    float64
 54   LIVE_Raw                  float64
 55   LIVE_StaticCompliance     float64
 56   LIVE_StaticPplat          float64
 57   LIVE_StaticPEEPe          float64
 58   LIVE_StaticPEEPi          float64
 59   LIVE_PEEPe_PEEPi          float64
 60   LIVE_EE                   float64
 61   LIVE_RQ                   float64
 62   LIVE_VO2                  float64
 63   LIVE_VCO2                 float64
 64   LIVE_VO2_M2               float64
 65   LIVE_VCO2_M2              float64
 66   OUTPUT_01                 float64
 67   OUTPUT_01_DETAIL          object
 68   OUTPUT_02                 float64
 69   OUTPUT_02_DETAIL          object
 70   OUTPUT_03                 float64
 71   OUTPUT_03_DETAIL          object
 72   OUTPUT_04                 float64
 73   OUTPUT_04_DETAIL          float64
 74   OUTPUT_05                 float64
 75   OUTPUT_05_DETAIL          float64
 76   OUTPUT_06                 float64
 77   OUTPUT_06_DETAIL          float64
 78   OUTPUT_07                 float64
 79   OUTPUT_07_DETAIL          float64
 80   OUTPUT_08                 float64
 81   OUTPUT_08_DETAIL          float64
 82   ABG_PH                    float64
 83   ABG_PCO2                  float64
 84   ABG_TCO2                  float64
 85   ABG_PO2                   float64
 86   ABG_FIO2                  float64
 87   ABG_BE                    float64
 88   ABG_HCO3                  float64
 89   ABG_O2SAT                 float64
 90   BICHEM_BS                 float64
 91   BICHEM_DTX                float64
 92   BICHEM_BUN                float64
 93   BICHEM_CR                 float64
 94   BICHEM_NA                 float64
 95   BICHEM_K                  float64
 96   BICHEM_HCO3               float64
 97   BICHEM_CL                 float64
 98   BICHEM_CA                 float64
 99   BICHEM_PO4                float64
 100  BICHEM_MG                 float64
 101  BICHEM_ALB                float64
 102  BICHEM_LACTATE            float64
dtypes: Int64(1), float64(85), int64(2), object(15)
memory usage: 93.6+ MB

In [11]:
bedccr

,R_ID,AdmissionID,HN,AN,ICUDate,ICUTime,HR,BP_SYS,BP_DIA,BP_TYPE,...,BICHEM_CR,BICHEM_NA,BICHEM_K,BICHEM_HCO3,BICHEM_CL,BICHEM_CA,BICHEM_PO4,BICHEM_MG,BICHEM_ALB,BICHEM_LACTATE
0,125576,1669892759015,NaN,NaN,01-12-2022,18,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,125582,1669892759015,NaN,NaN,01-12-2022,19,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,125592,1669892759015,NaN,NaN,01-12-2022,20,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,125614,1669892759015,NaN,NaN,01-12-2022,21,101.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,125627,1669892759015,NaN,NaN,01-12-2022,22,97.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118934,252740,1704022932311,NaN,NaN,22-01-2024,7,110.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118935,252752,1704022932311,NaN,NaN,22-01-2024,8,112.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118936,252765,1704022932311,NaN,NaN,22-01-2024,9,111.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118937,252778,1704022932311,NaN,NaN,22-01-2024,10,112.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118938,252791,1704022932311,NaN,NaN,22-01-2024,11,113.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
set(bedccr.ICUTime)

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23}

In [13]:
bedccr[['HN']].value_counts()

Series([], Name: count, dtype: int64)

In [14]:
bedccr[['MAP']]

        MAP
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
118934  NaN
118935  NaN
118936  NaN
118937  NaN
118938  NaN

[118939 rows x 1 columns]

In [15]:
bedccr[['MAP']].value_counts().sum()

14978

In [16]:
bedccr[["AdmissionID",'MAP']].notnull()

        AdmissionID    MAP
0              True  False
1              True  False
2              True  False
3              True  False
4              True  False
...             ...    ...
118934         True  False
118935         True  False
118936         True  False
118937         True  False
118938         True  False

[118939 rows x 2 columns]

In [17]:
bedccr['AdmissionID'][~bedccr['MAP'].isna()]

90112     1696316602500
90113     1695934699792
90114     1696148030611
90115     1696252269816
90116     1696216346847
              ...
106491    1700763910326
106492    1699267683825
106493    1699694472553
106494    1700379514766
106495    1697646653845
Name: AdmissionID, Length: 14978, dtype: Int64

In [18]:
data = bedccr.copy()

In [19]:
data[['MAP']][~data['MAP'].isna()]

       MAP
90112   79
90113   68
90114   86
90115   94
90116   72
...     ..
106491  65
106492  86
106493  83
106494  89
106495  76

[14978 rows x 1 columns]

In [20]:
data.MAP = pd.to_numeric(data.MAP, errors='coerce')
data.BP_SYS = pd.to_numeric(data.BP_SYS, errors='coerce')

In [21]:
data.MAP = data.MAP.astype('float64')
data.BP_SYS = data.BP_SYS.astype('float64')

#### shock

In [22]:
shock = data[(data['MAP']<65)|(data['BP_SYS']<90)]
shock

,R_ID,AdmissionID,HN,AN,ICUDate,ICUTime,HR,BP_SYS,BP_DIA,BP_TYPE,...,BICHEM_CR,BICHEM_NA,BICHEM_K,BICHEM_HCO3,BICHEM_CL,BICHEM_CA,BICHEM_PO4,BICHEM_MG,BICHEM_ALB,BICHEM_LACTATE
90128,219532,1696143306870,NaN,NaN,03-10-2023,22,64.0,84.0,59,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90147,219551,1696059005054,NaN,NaN,03-10-2023,23,87.0,85.0,63,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90156,219560,1696316602500,NaN,NaN,04-10-2023,0,131.0,124.0,74,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90167,219571,1696316602500,NaN,NaN,04-10-2023,1,130.0,124.0,74,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90180,219584,1696316602500,NaN,NaN,04-10-2023,2,129.0,149.0,80,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106171,235638,1697646653845,NaN,NaN,24-11-2023,15,96.0,79.0,73,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106194,235661,1697646653845,NaN,NaN,24-11-2023,16,94.0,86.0,78,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106227,235694,1699944510017,NaN,NaN,24-11-2023,19,119.0,88.0,64,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106403,235870,1699944510017,NaN,NaN,25-11-2023,7,103.0,83.0,67,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106484,235951,1699944510017,NaN,NaN,25-11-2023,13,105.0,85.0,63,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
shock['AdmissionID'].nunique()

55

In [24]:
shock['HN'].nunique()

0

### bedccr_lab

In [25]:
bedccr_lab = pd.read_csv(path+"icu_bedccr_lab.csv")
bedccr_lab = bedccr_lab.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
bedccr_lab.drop(['Unnamed: 0'], axis=1, inplace=True)
bedccr_lab.AdmissionID = bedccr_lab.AdmissionID.astype('Int64')
bedccr_lab.info()

<ipython-input-25-e74122528480>:1: DtypeWarning: Columns (17,18,19,20,21,22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  bedccr_lab = pd.read_csv(path+"icu_bedccr_lab.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34913 entries, 0 to 34912
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   R_ID            34913 non-null  int64
 1   AdmissionID     34913 non-null  Int64
 2   ICUDate         34913 non-null  object
 3   ICUTime         34913 non-null  int64
 4   ABG_PH          7178 non-null   float64
 5   ABG_PCO2        7175 non-null   float64
 6   ABG_TCO2        7105 non-null   float64
 7   ABG_PO2         7177 non-null   float64
 8   ABG_FIO2        6141 non-null   float64
 9   ABG_BE          7105 non-null   float64
 10  ABG_HCO3        7097 non-null   float64
 11  ABG_O2SAT       7119 non-null   float64
 12  BICHEM_BS       0 non-null      float64
 13  BICHEM_DTX      20703 non-null  object
 14  BICHEM_BUN      6745 non-null   float64
 15  BICHEM_CR       6755 non-null   float64
 16  BICHEM_NA       9419 non-null   object
 17  BICHEM_K        9420 non-null   object
 18  BICHEM_HCO3     9416 non-null   object
 19  BICHEM_CL       9418 non-null   object
 20  BICHEM_CA       6251 non-null   object
 21  BICHEM_PO4      6330 non-null   object
 22  BICHEM_MG       6495 non-null   float64
 23  BICHEM_ALB      6367 non-null   float64
 24  BICHEM_LACTATE  3990 non-null   object
 25  LAST_UPDATE     34913 non-null  int64
dtypes: Int64(1), float64(13), int64(3), object(9)
memory usage: 7.0+ MB

In [26]:
bedccr_lab

,R_ID,AdmissionID,ICUDate,ICUTime,ABG_PH,ABG_PCO2,ABG_TCO2,ABG_PO2,ABG_FIO2,ABG_BE,...,BICHEM_NA,BICHEM_K,BICHEM_HCO3,BICHEM_CL,BICHEM_CA,BICHEM_PO4,BICHEM_MG,BICHEM_ALB,BICHEM_LACTATE,LAST_UPDATE
0,159,1670884508074,13-12-2022,2,7.00,84.0,NaN,59.0,NaN,NaN,...,140,4.7,18.9,99,9.8,7.9,2.2,NaN,NaN,20221213220928
1,160,1670884508074,13-12-2022,8,NaN,NaN,NaN,NaN,NaN,NaN,...,138,3.6,27.8,95,8.7,5.8,1.9,4.3,14.4,20221213220928
2,161,1670884508074,13-12-2022,10,NaN,NaN,NaN,NaN,NaN,NaN,...,116,6.1,21.4,82,7.4,NaN,1.8,NaN,NaN,20221213220928
3,162,1670884508074,13-12-2022,13,7.45,42.0,30.5,71.0,60.0,4.6,...,137,3.1,25.7,97,8.3,3.4,1.7,3.8,NaN,20221213220928
4,163,1670884508074,13-12-2022,17,7.47,38.0,28.9,70.0,60.0,3.9,...,137,2.5,22.1,99,8.6,1.2,1.8,3.7,NaN,20221213220928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34908,40478,1704022932311,21-01-2024,4,7.16,19.0,7.4,124.0,NaN,-20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20240121080851
34909,40526,1704022932311,21-01-2024,17,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20240121220419
34910,40558,1704022932311,22-01-2024,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20240122055915
34911,40559,1704022932311,21-01-2024,22,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20240122055915
34912,40577,1704022932311,22-01-2024,7,7.28,28.0,13.5,88.0,40.0,-13.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20240122103433

In [27]:
bedccr_lab[bedccr_lab['AdmissionID'] == 1670884508074]

,R_ID,AdmissionID,ICUDate,ICUTime,ABG_PH,ABG_PCO2,ABG_TCO2,ABG_PO2,ABG_FIO2,ABG_BE,...,BICHEM_NA,BICHEM_K,BICHEM_HCO3,BICHEM_CL,BICHEM_CA,BICHEM_PO4,BICHEM_MG,BICHEM_ALB,BICHEM_LACTATE,LAST_UPDATE
0,159,1670884508074,13-12-2022,2,7.00,84.0,NaN,59.0,NaN,NaN,...,140,4.7,18.9,99,9.8,7.9,2.2,NaN,NaN,20221213220928
1,160,1670884508074,13-12-2022,8,NaN,NaN,NaN,NaN,NaN,NaN,...,138,3.6,27.8,95,8.7,5.8,1.9,4.3,14.4,20221213220928
2,161,1670884508074,13-12-2022,10,NaN,NaN,NaN,NaN,NaN,NaN,...,116,6.1,21.4,82,7.4,NaN,1.8,NaN,NaN,20221213220928
3,162,1670884508074,13-12-2022,13,7.45,42.0,30.5,71.0,60.0,4.6,...,137,3.1,25.7,97,8.3,3.4,1.7,3.8,NaN,20221213220928
4,163,1670884508074,13-12-2022,17,7.47,38.0,28.9,70.0,60.0,3.9,...,137,2.5,22.1,99,8.6,1.2,1.8,3.7,NaN,20221213220928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,3071,1670884508074,18-12-2022,5,NaN,NaN,NaN,NaN,NaN,NaN,...,151,2.4,23.8,116,8.1,0.7,2.2,2.8,NaN,20221218061900
1067,3072,1670884508074,18-12-2022,4,7.32,47.0,25.6,65.0,60.0,-2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20221218061900
1086,3097,1670884508074,18-12-2022,12,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20221218120845
1098,3222,1670884508074,18-12-2022,14,7.26,44.0,21.1,60.0,70.0,-7.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20221218142948
1144,3406,1670884508074,18-12-2022,15,7.23,45.0,20.2,60.0,80.0,-8.5,...,150,3.5,17.8,114,NaN,6.6,NaN,NaN,NaN,20221218151551

In [28]:
bedccr_lab[bedccr_lab['AdmissionID'] == 1670884508074].sort_values(by = 'LAST_UPDATE')

,R_ID,AdmissionID,ICUDate,ICUTime,ABG_PH,ABG_PCO2,ABG_TCO2,ABG_PO2,ABG_FIO2,ABG_BE,...,BICHEM_NA,BICHEM_K,BICHEM_HCO3,BICHEM_CL,BICHEM_CA,BICHEM_PO4,BICHEM_MG,BICHEM_ALB,BICHEM_LACTATE,LAST_UPDATE
0,159,1670884508074,13-12-2022,2,7.00,84.0,NaN,59.0,NaN,NaN,...,140,4.7,18.9,99,9.8,7.9,2.2,NaN,NaN,20221213220928
1,160,1670884508074,13-12-2022,8,NaN,NaN,NaN,NaN,NaN,NaN,...,138,3.6,27.8,95,8.7,5.8,1.9,4.3,14.4,20221213220928
2,161,1670884508074,13-12-2022,10,NaN,NaN,NaN,NaN,NaN,NaN,...,116,6.1,21.4,82,7.4,NaN,1.8,NaN,NaN,20221213220928
3,162,1670884508074,13-12-2022,13,7.45,42.0,30.5,71.0,60.0,4.6,...,137,3.1,25.7,97,8.3,3.4,1.7,3.8,NaN,20221213220928
4,163,1670884508074,13-12-2022,17,7.47,38.0,28.9,70.0,60.0,3.9,...,137,2.5,22.1,99,8.6,1.2,1.8,3.7,NaN,20221213220928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,3071,1670884508074,18-12-2022,5,NaN,NaN,NaN,NaN,NaN,NaN,...,151,2.4,23.8,116,8.1,0.7,2.2,2.8,NaN,20221218061900
1067,3072,1670884508074,18-12-2022,4,7.32,47.0,25.6,65.0,60.0,-2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20221218061900
1086,3097,1670884508074,18-12-2022,12,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20221218120845
1098,3222,1670884508074,18-12-2022,14,7.26,44.0,21.1,60.0,70.0,-7.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20221218142948
1144,3406,1670884508074,18-12-2022,15,7.23,45.0,20.2,60.0,80.0,-8.5,...,150,3.5,17.8,114,NaN,6.6,NaN,NaN,NaN,20221218151551

In [29]:
ccr_lab_G = bedccr_lab[["AdmissionID", "ICUDate" , "ICUTime",'LAST_UPDATE']][bedccr_lab["AdmissionID"] == 1683894155455]

In [30]:
ccr_lab_G.groupby(by = [ "ICUDate" , "ICUTime",'LAST_UPDATE']).value_counts()

ICUDate     ICUTime  LAST_UPDATE     AdmissionID
01-06-2023  0        20230601061945  1683894155455    1
            1        20230601061945  1683894155455    1
            4        20230601061946  1683894155455    1
            5        20230601061946  1683894155455    1
            7        20230601101010  1683894155455    1
                                                     ..
31-05-2023  17       20230531194618  1683894155455    1
            18       20230531194616  1683894155455    1
            19       20230531194617  1683894155455    1
            22       20230531235548  1683894155455    1
            23       20230531235548  1683894155455    1
Name: count, Length: 299, dtype: int64

### bedmonitortrack

In [31]:
bedmonitortrack = pd.read_csv(path+"icu_bedmonitortrack.csv")
bedmonitortrack = bedmonitortrack.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
bedmonitortrack.drop(['Unnamed: 0'], axis=1, inplace=True)
bedmonitortrack.AdmissionID = bedmonitortrack.AdmissionID.astype('Int64')
bedmonitortrack.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3877026 entries, 0 to 3877025
Data columns (total 16 columns):
 #   Column       Dtype
---  ------       -----
 0   R_ID         int64
 1   BedID        object
 2   AdmissionID  Int64
 3   ICUDate      object
 4   ICUTime      int64
 5   HR           float64
 6   RR           float64
 7   BP_SYS       float64
 8   BP_DIA       float64
 9   BP_TYPE      object
 10  MAP          float64
 11  Temp         float64
 12  O2SAT        float64
 13  PPV          float64
 14  CVP          float64
 15  LastUpdate   int64
dtypes: Int64(1), float64(9), int64(3), object(3)
memory usage: 477.0+ MB

In [32]:
bedmonitortrack

,R_ID,BedID,AdmissionID,ICUDate,ICUTime,HR,RR,BP_SYS,BP_DIA,BP_TYPE,MAP,Temp,O2SAT,PPV,CVP,LastUpdate
0,6231807,MICU203,1683894155455,01-06-2023,0,93.0,NaN,127.0,61.0,ABP,80.0,NaN,98.0,NaN,11.0,20230601000000
1,6231808,MICU202,1685281139464,01-06-2023,0,96.0,18.0,151.0,79.0,ABP,107.0,NaN,100.0,NaN,NaN,20230601000000
2,6231809,MICU208,1685543221131,01-06-2023,0,90.0,21.0,159.0,78.0,NBP,100.0,NaN,98.0,NaN,4.0,20230601000000
3,6231810,MICU205,1684298259563,01-06-2023,0,76.0,11.0,138.0,55.0,NBP,80.0,NaN,95.0,NaN,NaN,20230601000000
4,6231811,MICU101,1685219929689,01-06-2023,0,81.0,18.0,119.0,71.0,ABP,88.0,NaN,98.0,5.0,NaN,20230601000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3877021,10360308,MICU202,1704022932311,22-01-2024,11,NaN,NaN,16777.0,16777.0,ABP,16777.0,NaN,NaN,NaN,NaN,20240122112930
3877022,10360321,MICU202,1704022932311,22-01-2024,11,NaN,NaN,NaN,NaN,ABP,16777.0,NaN,NaN,NaN,NaN,20240122113031
3877023,10360331,MICU202,1704022932311,22-01-2024,11,NaN,NaN,NaN,NaN,ABP,16777.0,NaN,NaN,NaN,NaN,20240122113132
3877024,10360372,MICU202,1704022932311,22-01-2024,11,NaN,NaN,NaN,NaN,ABP,5.0,NaN,NaN,NaN,-33.0,20240122113443
3877025,10360384,MICU202,1704022932311,22-01-2024,11,NaN,NaN,NaN,NaN,ABP,5.0,NaN,NaN,NaN,-36.0,20240122113544

In [33]:
# set(bedmonitortrack.ICUTime)

In [34]:
moniter_G = bedmonitortrack[["AdmissionID", "ICUDate" , "ICUTime","LastUpdate"]][bedmonitortrack["AdmissionID"] == 1683894155455]

In [35]:
moniter_G.groupby(by = [ "ICUDate" , "ICUTime",]).value_counts()

ICUDate     ICUTime  AdmissionID    LastUpdate
01-06-2023  0        1683894155455  20230601000000    1
                                    20230601000101    1
                                    20230601005559    1
                                    20230601005356    1
                                    20230601005255    1
                                                     ..
14-06-2023  9        1683894155455  20230614090303    1
                                    20230614090202    1
                                    20230614090101    1
                                    20230614090000    1
                                    20230614094212    1
Name: count, Length: 19102, dtype: int64

In [36]:
moniter_G.groupby(by = [ "ICUDate" , "ICUTime","LastUpdate"]).value_counts()

ICUDate     ICUTime  LastUpdate      AdmissionID
01-06-2023  0        20230601000000  1683894155455    1
                     20230601000101  1683894155455    1
                     20230601000202  1683894155455    1
                     20230601000303  1683894155455    1
                     20230601000404  1683894155455    1
                                                     ..
14-06-2023  9        20230614093808  1683894155455    1
                     20230614093909  1683894155455    1
                     20230614094010  1683894155455    1
                     20230614094111  1683894155455    1
                     20230614094212  1683894155455    1
Name: count, Length: 19102, dtype: int64

### intake_output

In [58]:
intake_output = pd.read_csv(path+"icu_intake_output.csv")
intake_output = intake_output.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
intake_output.drop(['Unnamed: 0'], axis=1, inplace=True)
intake_output.AdmissionID = intake_output.AdmissionID.astype('Int64')
intake_output.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   R_ID                397 non-null    int64
 1   AdmissionID         397 non-null    Int64
 2   ICUDate             397 non-null    object
 3   TotalIntake_Shift1  390 non-null    float64
 4   TotalIntake_Shift2  390 non-null    float64
 5   TotalIntake_Shift3  390 non-null    float64
 6   TotalIntake_24hr    390 non-null    float64
 7   TotalIntake_IV      390 non-null    float64
 8   TotalIntake_ORAL    390 non-null    float64
 9   TotalOuput_Shift1   397 non-null    int64
 10  TotalOuput_Shift2   397 non-null    float64
 11  TotalOuput_Shift3   397 non-null    int64
 12  TotalOuput_24hr     397 non-null    float64
 13  IO_Shift1           397 non-null    float64
 14  IO_Shift2           397 non-null    float64
 15  IO_Shift3           397 non-null    float64
 16  IO_24hr             397 non-null    float64
 17  LastUpdate          397 non-null    int64
dtypes: Int64(1), float64(12), int64(4), object(1)
memory usage: 56.3+ KB

In [59]:
intake_output

,R_ID,AdmissionID,ICUDate,TotalIntake_Shift1,TotalIntake_Shift2,TotalIntake_Shift3,TotalIntake_24hr,TotalIntake_IV,TotalIntake_ORAL,TotalOuput_Shift1,TotalOuput_Shift2,TotalOuput_Shift3,TotalOuput_24hr,IO_Shift1,IO_Shift2,IO_Shift3,IO_24hr,LastUpdate
0,14,1704022932311,19-01-2024,992.6,1845.2,1148.2,3986.0,2946.0,1040.0,470,400.0,330,1200.0,522.6,1445.2,818.2,2786.0,20240125061958
1,27,1704022932311,18-01-2024,930.4,692.8,1106.3,2729.5,1313.5,1380.0,990,840.0,565,2395.0,-59.6,-147.2,541.3,334.5,20240125061946
2,29,1699267683825,07-12-2023,93.0,0.0,0.0,93.0,93.0,0.0,350,0.0,0,350.0,-257.0,0.0,0.0,-257.0,20240119085250
3,30,1699267683825,06-11-2023,0.0,594.9,751.1,1346.0,1346.0,0.0,0,780.0,420,1200.0,0.0,-185.1,331.1,146.0,20240119081442
4,34,1699694472553,25-11-2023,542.1,433.8,533.8,1509.7,689.7,820.0,125,530.0,550,1205.0,417.1,-96.2,-16.2,304.7,20240429091232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,1702,1690203672771,29-07-2023,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0.0,0.0,0.0,0.0,0.0,20240412094428
393,1703,1697963915143,25-10-2023,787.1,262.9,0.0,1050.0,650.0,400.0,400,800.0,0,1200.0,387.1,-537.1,0.0,-150.0,20240412100524
394,1713,1702867663447,19-12-2023,1305.1,110.6,100.0,1515.7,1385.7,130.0,255,65.0,0,320.0,1050.1,45.6,100.0,1195.7,20240413055641
395,1714,1702867663447,18-12-2023,389.3,1049.0,719.8,2158.1,1658.1,500.0,120,190.0,1050,1360.0,269.3,859.0,-330.2,798.1,20240413055644
396,1790,1675097068636,04-03-2023,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0.0,0.0,0.0,0.0,0.0,20240418100614

In [41]:
#intake_output['ICUDate'] = pd.to_datetime(intake_output['ICUDate'], errors='coerce')
#intake_output['ICUDate'] = intake_output['ICUDate'].dt.strftime('%Y-%m-%d')

<ipython-input-41-076839a0a21e>:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  intake_output['ICUDate'] = pd.to_datetime(intake_output['ICUDate'], errors='coerce')

In [60]:
intake_output[['ICUDate']]

        ICUDate
0    19-01-2024
1    18-01-2024
2    07-12-2023
3    06-11-2023
4    25-11-2023
..          ...
392  29-07-2023
393  25-10-2023
394  19-12-2023
395  18-12-2023
396  04-03-2023

[397 rows x 1 columns]

### snomed

In [44]:
snomed = pd.read_csv(path+"icu_snomed.csv")
snomed = snomed.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
snomed.drop(['Unnamed: 0'], axis=1, inplace=True)
snomed.AdmissionID = snomed.AdmissionID.astype('Int64')
# snomed.VN = snomed.VN.astype('Int64')
snomed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7661 entries, 0 to 7660
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   R_ID              7661 non-null   object
 1   DATA_TYPE         7661 non-null   object
 2   AdmissionID       7661 non-null   Int64
 3   HN                7661 non-null   object
 4   VN                7661 non-null   object
 5   AN                7661 non-null   object
 6   conceptId         7661 non-null   int64
 7   ICD10_CODE        4905 non-null   object
 8   definitionStatus  7661 non-null   object
 9   term              7661 non-null   object
 10  term_long         7661 non-null   object
 11  USER_UPDATE       7538 non-null   object
 12  CREATE_DATE       7661 non-null   int64
 13  LAST_UPDATE       7661 non-null   int64
 14  SNOMED_STATUS     7661 non-null   object
dtypes: Int64(1), int64(3), object(11)
memory usage: 905.4+ KB

In [45]:
snomed = snomed[snomed['SNOMED_STATUS']!='DELETE']
snomed

,R_ID,DATA_TYPE,AdmissionID,HN,VN,AN,conceptId,ICD10_CODE,definitionStatus,term,term_long,USER_UPDATE,CREATE_DATE,LAST_UPDATE,SNOMED_STATUS
0,SCT1670376527727,PDX,1670150398986,IB4480,10105842,I22-046737,55464009,M32.9,PRIMITIVE,Systemic lupus erythematosus,Systemic lupus erythematosus (disorder),md64311,20221207082847,20221207082847,ACTIVE
1,SCT1670376548909,SDX,1670150398986,IB4480,10105842,I22-046737,78129009,M31.1,PRIMITIVE,Thrombotic thrombocytopenic purpura,Thrombotic thrombocytopenic purpura (disorder),md64311,20221207082908,20221207082908,ACTIVE
8,SCT1670380999244,PDX,1670066559142,FW0443,10122372,I22-047245,77377001,A27.9,FULLY_DEFINED,Leptospirosis,Leptospirosis (disorder),md64311,20221207094319,20221207094319,ACTIVE
9,SCT1670381016954,SDX,1670066559142,FW0443,10122372,I22-047245,14669001,N17.9,FULLY_DEFINED,AKI - acute kidney injury,Acute renal failure syndrome (disorder),md64311,20221207094336,20221207094336,ACTIVE
10,SCT1670381029078,SDX,1670066559142,FW0443,10122372,I22-047245,44730006,N18.9,FULLY_DEFINED,Uremia,Uremia (disorder),md64311,20221207094349,20221207094349,ACTIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7656,SCT1712917654905,SDX,1701946977904,DL9390,11442076,I23-046521,90272000,NaN,PRIMITIVE,Enterococcus faecium,Enterococcus faecium (organism),md61307,20240412172734,20240412172734,ACTIVE
7657,SCT1712917710358,SDX,1701946977904,DL9390,11442076,I23-046521,112283007,NaN,PRIMITIVE,Escherichia coli,Escherichia coli (organism),md61307,20240412172830,20240412172830,ACTIVE
7658,SCT1712917721246,SDX,1701946977904,DL9390,11442076,I23-046521,52499004,NaN,PRIMITIVE,Pseudomonas aeruginosa,Pseudomonas aeruginosa (organism),md61307,20240412172841,20240412172841,ACTIVE
7659,SCT1712918091600,HXSX,1701946977904,DL9390,11442076,I23-046521,447837008,NaN,FULLY_DEFINED,Non-invasive positive pressure ventilation,Non-invasive positive pressure ventilation (re...,md61307,20240412173451,20240412173451,ACTIVE
7660,SCT1712918109634,HXSX,1701946977904,DL9390,11442076,I23-046521,392247006,NaN,FULLY_DEFINED,Arterial catheterization,Insertion of catheter into artery (procedure),md61307,20240412173509,20240412173509,ACTIVE

### redcap

In [46]:
redcap = pd.read_csv(path+"redcap_2023_12-31.csv")
redcap = redcap.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
redcap.rename(columns = {'an':'AN', 'hn':'HN'}, inplace = True)
redcap.drop(['Unnamed: 0'], axis=1, inplace=True)
redcap.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 152 columns):
 #    Column               Dtype
---   ------               -----
 0    record_id            int64
 1    redcap_event         object
 2    HN                   object
 3    AN                   object
 4    icu_kku              int64
 5    h_adm_date           object
 6    icu_adm_date         object
 7    sex                  int64
 8    age                  int64
 9    time_to_icu          int64
 10   pdx                  float64
 11   reason_icu           float64
 12   insurance            float64
 13   insurance_oth        object
 14   postcode             float64
 15   weight               float64
 16   height               float64
 17   bmi                  float64
 18   pregnancy            float64
 19   gestatiion_wk        float64
 20   ckd                  float64
 21   ckd_stage            float64
 22   h_adm_source         float64
 23   icu_adm_source       int64
 24   elective_surg        float64
 25   arrest_bf            int64
 26   cci___1              int64
 27   cci___2              int64
 28   cci___3              int64
 29   cci___4              int64
 30   cci___5              int64
 31   cci___6              int64
 32   cci___7              int64
 33   cci___8              int64
 34   cci___9              int64
 35   cci___10             int64
 36   cci___11             int64
 37   cci___12             int64
 38   cci___13             int64
 39   cci___14             int64
 40   cci___15             int64
 41   cci___16             int64
 42   cci___17             int64
 43   cci___18             int64
 44   cci___19             int64
 45   cci___0              int64
 46   cci_total            float64
 47   lactate_24h          float64
 48   apache_3             float64
 49   sofa                 float64
 50   sap_2                float64
 51   mv_icu               float64
 52   num_ettube           float64
 53   mv_start_1           object
 54   mv_end_1             object
 55   mv_start_2           object
 56   mv_end_2             object
 57   mv_start_3           object
 58   mv_end_3             object
 59   mv_start_4           object
 60   mv_end_4             object
 61   mv_duration          float64
 62   niv                  float64
 63   ecmo                 float64
 64   iabp                 float64
 65   hemoperfusion        float64
 66   shock                float64
 67   shock_type___1       int64
 68   shock_type___2       int64
 69   shock_type___3       int64
 70   shock_type___4       int64
 71   shock_type___5       int64
 72   ino_vaso             float64
 73   vaso_start_date      object
 74   vaso_stop_date       object
 75   shock_reversal_time  float64
 76   ttm                  float64
 77   plex                 float64
 78   pan_inf              float64
 79   thrombolytic_ami     float64
 80   frailty              float64
 81   delirium             float64
 82   press_inj            float64
 83   press_inj_stage      float64
 84   cumm_fluid           float64
 85   fluid_overload       float64
 86   aki                  float64
 87   aki_onset            object
 88   aki_stage            float64
 89   aki_date             object
 90   time_icutoaki        float64
 91   aki_etio___1         int64
 92   aki_etio___2         int64
 93   aki_etio___3         int64
 94   aki_etio___4         int64
 95   aki_etio___5         int64
 96   aki_etio___6         int64
 97   aki_etio___7         int64
 98   aki_etio___8         int64
 99   aki_etio___9         int64
 100  aki_etio___10        int64
 101  aki_etio___11        int64
 102  aki_etio___12        int64
 103  fst                  float64
 104  fst_response         float64
 105  diuretic_bf          float64
 106  nephrolist_bf___1    int64
 107  nephrolist_bf___2    int64
 108  nephrolist_bf___3    int64
 109  nephrolist_bf___4    int64
 110  nephrolist_bf___5    int64
 111  nephrolist_bf___6    int64
 112  nephrolist_bf___7    int64
 113  nephrolist_bf___8    int64
 114  nephrolist_bf___9    int64
 115  nephrolist_bf___10   int64
 116  nephrolist_bf___0    int64
 117  nephrolist_af___1    int64
 118  nephrolist_af___2    int64
 119  nephrolist_af___3    int64
 120  nephrolist_af___4    int64
 121  nephrolist_af___5    int64
 122  nephrolist_af___6    int64
 123  nephrolist_af___7    int64
 124  nephrolist_af___8    int64
 125  nephrolist_af___9    int64
 126  nephrolist_af___10   int64
 127  nephrolist_af___0    int64
 128  rrt                  float64
 129  rrt_start            object
 130  rrt_type___1         int64
 131  rrt_type___2         int64
 132  rrt_type___3         int64
 133  rrt_type___4         int64
 134  rfd_28               float64
 135  icu_dc_dest          float64
 136  icu_los              float64
 137  h_dc_dest            float64
 138  h_los                float64
 139  h_mort               float64
 140  icu_mort             float64
 141  mort_28              float64
 142  surv_28              float64
 143  mort_90              float64
 144  surv_90              float64
 145  vfd_28               float64
 146  sfd_28               float64
 147  cvs                  int64
 148  neuro                int64
 149  cirrhosis            int64
 150  dm                   int64
 151  cancer               int64
dtypes: float64(58), int64(75), object(19)
memory usage: 622.4+ KB

In [47]:
redcap['HN'].nunique()

491

In [48]:
redcap['AN'].nunique()

524

In [49]:
redcap.sort_values(by=['icu_adm_date','time_to_icu'], ascending=True, inplace=True)

In [50]:
redcap

,record_id,redcap_event,HN,AN,icu_kku,h_adm_date,icu_adm_date,sex,age,time_to_icu,...,surv_28,mort_90,surv_90,vfd_28,sfd_28,cvs,neuro,cirrhosis,dm,cancer
0,141,baseline_and_day_0,JR8123,I22-047074,1,2022-12-01,2022-12-01,1,66,0,...,28.0,0.0,90.0,25.9,28.00,0,0,0,0,0
1,142,baseline_and_day_0,CC7538,I22-047181,1,2022-12-02,2022-12-02,0,85,0,...,28.0,0.0,90.0,26.3,26.35,1,1,0,1,0
5,150,baseline_and_day_0,DN2086,I22-047178,2,2022-12-02,2022-12-02,0,82,0,...,28.0,0.0,90.0,26.2,28.00,0,1,0,1,1
2,146,baseline_and_day_0,FW0443,I22-047245,2,2022-12-03,2022-12-03,1,42,0,...,28.0,0.0,90.0,24.1,24.77,0,0,0,0,0
4,148,baseline_and_day_0,FJ6718,I22-046368,2,2022-11-28,2022-12-03,0,83,5,...,28.0,0.0,90.0,27.5,28.00,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,928,baseline_and_day_0,HT8560,I23-049107,1,2023-12-20,2023-12-28,0,67,8,...,18.0,1.0,18.0,0.0,0.00,0,0,0,1,0
518,924,baseline_and_day_0,GO3388,I23-050413,2,2023-12-30,2023-12-30,0,76,0,...,NaN,NaN,NaN,25.6,NaN,0,0,1,1,0
519,925,baseline_and_day_0,KY1203,I23-050381,2,2023-12-30,2023-12-30,0,30,0,...,28.0,NaN,NaN,22.0,28.00,0,0,0,0,0
520,926,baseline_and_day_0,HN5310,I23-050437,2,2023-12-31,2023-12-31,1,96,0,...,22.0,1.0,22.0,0.0,0.00,0,1,0,1,0
521,927,baseline_and_day_0,EY9650,I23-050403,1,2023-12-31,2023-12-31,0,65,0,...,6.0,1.0,6.0,0.0,0.00,0,0,0,0,1

In [51]:
redcap = redcap.drop_duplicates(subset=['HN'], keep='first')
redcap

,record_id,redcap_event,HN,AN,icu_kku,h_adm_date,icu_adm_date,sex,age,time_to_icu,...,surv_28,mort_90,surv_90,vfd_28,sfd_28,cvs,neuro,cirrhosis,dm,cancer
0,141,baseline_and_day_0,JR8123,I22-047074,1,2022-12-01,2022-12-01,1,66,0,...,28.0,0.0,90.0,25.9,28.00,0,0,0,0,0
1,142,baseline_and_day_0,CC7538,I22-047181,1,2022-12-02,2022-12-02,0,85,0,...,28.0,0.0,90.0,26.3,26.35,1,1,0,1,0
5,150,baseline_and_day_0,DN2086,I22-047178,2,2022-12-02,2022-12-02,0,82,0,...,28.0,0.0,90.0,26.2,28.00,0,1,0,1,1
2,146,baseline_and_day_0,FW0443,I22-047245,2,2022-12-03,2022-12-03,1,42,0,...,28.0,0.0,90.0,24.1,24.77,0,0,0,0,0
4,148,baseline_and_day_0,FJ6718,I22-046368,2,2022-11-28,2022-12-03,0,83,5,...,28.0,0.0,90.0,27.5,28.00,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,928,baseline_and_day_0,HT8560,I23-049107,1,2023-12-20,2023-12-28,0,67,8,...,18.0,1.0,18.0,0.0,0.00,0,0,0,1,0
518,924,baseline_and_day_0,GO3388,I23-050413,2,2023-12-30,2023-12-30,0,76,0,...,NaN,NaN,NaN,25.6,NaN,0,0,1,1,0
519,925,baseline_and_day_0,KY1203,I23-050381,2,2023-12-30,2023-12-30,0,30,0,...,28.0,NaN,NaN,22.0,28.00,0,0,0,0,0
520,926,baseline_and_day_0,HN5310,I23-050437,2,2023-12-31,2023-12-31,1,96,0,...,22.0,1.0,22.0,0.0,0.00,0,1,0,1,0
521,927,baseline_and_day_0,EY9650,I23-050403,1,2023-12-31,2023-12-31,0,65,0,...,6.0,1.0,6.0,0.0,0.00,0,0,0,0,1

In [52]:
set(redcap.redcap_event)

{'baseline_and_day_0'}

In [53]:
set(redcap.mv_icu)

{0.0, 1.0, nan}

In [54]:
len(set(redcap['HN'][redcap.shock ==1]))

289

# convert `ICUDate` and `ICUTime` to datetime format

In [55]:
admission['ICUDateTime'] = pd.to_datetime([str(i)+' '+str(j) for i,j in zip(admission['DateRecord'],admission['TimeRecord'])], format='%Y-%m-%d %H:%M')
bedccr['ICUDateTime'] = pd.to_datetime([str(i)+' '+str(j) for i,j in zip(bedccr['ICUDate'],bedccr['ICUTime'])], format='%d-%m-%Y %H')
bedccr_lab['ICUDateTime'] = pd.to_datetime([str(i)+' '+str(j) for i,j in zip(bedccr_lab['ICUDate'],bedccr_lab['ICUTime'])], format='%d-%m-%Y %H')
bedmonitortrack['ICUDateTime'] = pd.to_datetime([str(i)+' '+str(j) for i,j in zip(bedmonitortrack['ICUDate'],bedmonitortrack['ICUTime'])], format='%d-%m-%Y %H')

<ipython-input-55-daa0b22f90d1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  admission['ICUDateTime'] = pd.to_datetime([str(i)+' '+str(j) for i,j in zip(admission['DateRecord'],admission['TimeRecord'])], format='%Y-%m-%d %H:%M')

In [61]:
redcap['h_adm_date'] = pd.to_datetime(redcap['h_adm_date'], format='%Y-%m-%d')
redcap['icu_adm_date'] = pd.to_datetime(redcap['icu_adm_date'], format='%Y-%m-%d')
admission['DateRecord'] = pd.to_datetime(admission['DateRecord'], format='%Y-%m-%d')
admission['TimeRecord'] = pd.to_datetime(admission['TimeRecord'], format='%H:%M')
bedccr['ICUDate'] = pd.to_datetime(bedccr['ICUDate'], format='%d-%m-%Y')
bedccr['ICUTime'] = pd.to_datetime(bedccr['ICUTime'], format='%H')
bedccr_lab['ICUDate'] = pd.to_datetime(bedccr_lab['ICUDate'], format='%d-%m-%Y')
bedccr_lab['ICUTime'] = pd.to_datetime(bedccr_lab['ICUTime'], format='%H')
bedmonitortrack['ICUDate'] = pd.to_datetime(bedmonitortrack['ICUDate'], format='%d-%m-%Y')
bedmonitortrack['ICUTime'] = pd.to_datetime(bedmonitortrack['ICUTime'], format='%H')
intake_output['ICUDate'] = pd.to_datetime(intake_output['ICUDate'], format='%d-%m-%Y')

<ipython-input-61-9fda3d391285>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  redcap['h_adm_date'] = pd.to_datetime(redcap['h_adm_date'], format='%Y-%m-%d')
<ipython-input-61-9fda3d391285>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  redcap['icu_adm_date'] = pd.to_datetime(redcap['icu_adm_date'], format='%Y-%m-%d')
<ipython-input-61-9fda3d391285>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  admission['DateRecord'] = pd.to_datetime(admission['DateRecord'], format='%Y-%m-%d')
<ipython-input-61-9fda3d391285>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  admission['TimeRecord'] = pd.to_datetime(admission['TimeRecord'], format='%H:%M')

# Join DataFrames

### join(admission, redcap)

In [ ]:
df = pd.merge(admission, redcap, on=['AN','HN'], how='left')#,indicator=True)
df

In [ ]:
# # Remove records in left table that do not have info from right table
# df = df.drop(df[df['DateTimeRecord'].isna()].index)
# df[df['DateTimeRecord'].isna()]
print(df['AdmissionID'].nunique(), df['HN'].nunique(), df['AN'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['AN'].nunique())

In [ ]:
df.info(verbose=True)

### join( , snomed)

In [ ]:
df1 = pd.merge(df, snomed, on=['AN','HN'], how='left', suffixes=("","_snomed"), indicator=True)

In [ ]:
df1.info(verbose=True)

In [ ]:
df1["_merge"].value_counts()

In [ ]:
df1[['HN','AN','record_id','R_ID','AdmissionID', 'AdmissionID_snomed', 'VN','VN_snomed']]

In [ ]:
# print(type(df['VN_'][0]), type(df['VN_snomed'][0]))
# df[['HN','AN','record_id','R_ID','AdmissionID', 'VN_','VN_snomed']][df['VN_']!=df['VN_snomed']]
compare_id = df1[(pd.notna(df1['AdmissionID'])) & (pd.notna(df1['AdmissionID_snomed'])) & (df1['AdmissionID']!=df1['AdmissionID_snomed'])][['AN','HN','AdmissionID','AdmissionID_snomed']]
compare_id

In [ ]:
print(df1['AdmissionID'].nunique(), df1['HN'].nunique(), df1['AN'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['AN'].nunique())
print(snomed['AdmissionID'].nunique(), snomed['HN'].nunique(), snomed['AN'].nunique())

In [ ]:
print(df1['AdmissionID'].nunique(), df1['AdmissionID_snomed'].nunique())
print(df1['VN'].nunique(), df1['VN_snomed'].nunique())

### join( , intake_output)

In [ ]:
df2 = pd.merge(df1, intake_output,
              left_on=['AdmissionID', 'DateRecord'],
              right_on=['AdmissionID', 'ICUDate'],
              how='left', suffixes=("","_io"), indicator='exist0')

In [ ]:
df2.info(verbose=True)

In [ ]:
print(df2['AdmissionID'].nunique(), df2['HN'].nunique(), df2['AN'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['AN'].nunique())
print(intake_output['AdmissionID'].nunique())

In [ ]:
df2

In [ ]:
df2[['DateRecord', 'TimeRecord', 'ICUDate','exist0']][df2['exist0'] == 'left_only']

In [ ]:
df2["exist0"].value_counts()

In [ ]:
df2[['DateRecord', 'TimeRecord', 'ICUDate']][~df2['ICUDate'].isna()]

### join( , bedccr)

In [ ]:
table = pd.merge(df2, bedccr, on=['AdmissionID', 'ICUDate'],
                     how='left', suffixes=('','_bed'), indicator='exist1')
table

In [ ]:
table.info(verbose=True)

In [ ]:
print(df['AdmissionID'].nunique(), df['HN'].nunique(), df['AN'].nunique())
print(table['AdmissionID'].nunique(), table['HN'].nunique(), table['AN'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['HN'].nunique())
print(bedccr['AdmissionID'].nunique(), bedccr['HN'].nunique(), bedccr['AN'].nunique())
#ที่เป็น 568 0 0 เพราะว่าที่ตาราง bedccr ไม่มี HN, AN

In [ ]:
print(len(set(df['AdmissionID']) & set(bedccr['AdmissionID'])))
print(len(set(table['AdmissionID']) & set(bedccr['AdmissionID'])))

### join( , bedccr_lab)

In [ ]:
# table2 = pd.merge(table, bedccr_lab, on=['AdmissionID', 'ICUDateTime'],
#                      how='left', suffixes=('','_lab'), indicator='exist2')
table2 = pd.merge(table, bedccr_lab, on=['AdmissionID', 'ICUDate'],
                     how='left', suffixes=('','_lab'), indicator='exist2')

table2

In [ ]:
table2.info(verbose=True)

In [ ]:
print(len(set(df2['AdmissionID']) & set(bedccr_lab['AdmissionID'])))
print(len(set(table2['AdmissionID']) & set(bedccr_lab['AdmissionID'])))

In [ ]:
print(df2['AdmissionID'].nunique(), df2['HN'].nunique(), df2['AN'].nunique())
print(table2['AdmissionID'].nunique(), table2['HN'].nunique(), table2['AN'].nunique())
print(bedccr_lab['AdmissionID'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['AN'].nunique())

In [ ]:
table2['exist2'].value_counts()

In [ ]:
print(len(set(table['AdmissionID']) & set(bedccr_lab['AdmissionID'])))
print(len(set(table['ICUDate']) & set(bedccr_lab['ICUDate'])))

In [ ]:
print(set(table['ICUDateTime']) & set(bedccr_lab['ICUDateTime']))

In [ ]:
len(set(table2[table2['exist2'] == "both"]['AdmissionID']))

In [ ]:
#table.to_excel(path+'work_files/icu_merge_except_monitortrack_05-14-24.xlsx')

### join(all)

In [ ]:
table3 = pd.merge(table2, bedmonitortrack, on=['AdmissionID', 'ICUDateTime'],
                     how='left', suffixes=('','_monitor'), indicator='exist3')
table3

In [ ]:
table3.info(verbose=True)

In [ ]:
print(len(set(df2['AdmissionID']) & set(bedmonitortrack['AdmissionID'])))
print(len(set(table3['AdmissionID']) & set(bedmonitortrack['AdmissionID'])))

In [ ]:
table_276 = table3[table3['AdmissionID'].isin(bedmonitortrack['AdmissionID'])]
table_276

In [ ]:
#table_276.to_csv(path+'work_files/table_276.csv')

# ผู้ป่วยที่ช็อค

In [ ]:
table3

In [ ]:
shock = table3.dropna(subset=['MAP', 'BP_SYS'])
shock

In [ ]:
shock['MAP'] = pd.to_numeric(shock['MAP'], errors='coerce')
shock['BP_SYS'] = pd.to_numeric(shock['BP_SYS'], errors='coerce')

# Filter the DataFrame
shock_filtered = shock[(shock['MAP'] < 65) | (shock['BP_SYS'] < 90)]
shock_filtered

# Join by tonry

## join(redcap,snomed)

In [ ]:
tr1 = pd.merge(redcap, snomed, on=['AN','HN'], how='left', suffixes=("","_snomed"), indicator=True)

In [ ]:
tr1.info(verbose=True)

In [ ]:
tr1["_merge"].value_counts()

In [ ]:
tr1[['HN','AN','record_id','R_ID']]

In [ ]:
print(tr1['AdmissionID'].nunique(), tr1['HN'].nunique(), tr1['AN'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['AN'].nunique())
print(snomed['AdmissionID'].nunique(), snomed['HN'].nunique(), snomed['AN'].nunique())

In [ ]:
print(df1['AdmissionID'].nunique(), df1['AdmissionID_snomed'].nunique())
print(df1['VN'].nunique(), df1['VN_snomed'].nunique())

##join(, intake_output)

In [ ]:
intake_output.head()

In [ ]:
tr1.head()

In [ ]:
#tr2 = pd.merge(tr1, intake_output,
#             on=['AdmissionID',  'ICUDate'],
#             how='right', suffixes=("","_io"), indicator='exist0')

#Join tonnaw

### join(admission, redcap)

In [62]:
tn = pd.merge(admission, redcap, on=['AN','HN'], how='left')#,indicator=True)
tn

,AdmissionID,HN,VN,AN,Age,Sex,DateRecord,TimeRecord,ICUDateTime,record_id,...,surv_28,mort_90,surv_90,vfd_28,sfd_28,cvs,neuro,cirrhosis,dm,cancer
0,1669892759015,JR8123,10116794,I22-047074,66 ปี,ชาย,2022-12-01,1900-01-01 18:05:00,2022-12-01 18:05:00,141.0,...,28.0,0.0,90.0,25.9,28.00,0.0,0.0,0.0,0.0,0.0
1,1669968929608,BW3848,9945849,I22-040013,74 ปี,หญิง,2022-12-02,1900-01-01 15:15:00,2022-12-02 15:15:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1669986847225,DN2086,10119971,I22-047178,82 ปี,หญิง,2022-12-02,1900-01-01 20:14:00,2022-12-02 20:14:00,150.0,...,28.0,0.0,90.0,26.2,28.00,0.0,1.0,0.0,1.0,1.0
3,1669987593264,CC7538,10120136,I22-047181,85 ปี,หญิง,2022-12-02,1900-01-01 20:26:00,2022-12-02 20:26:00,142.0,...,28.0,0.0,90.0,26.3,26.35,1.0,1.0,0.0,1.0,0.0
4,1670066559142,FW0443,10122372,I22-047245,42 ปี,ชาย,2022-12-03,1900-01-01 18:22:00,2022-12-03 18:22:00,146.0,...,28.0,0.0,90.0,24.1,24.77,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,1703773563260,HT8560,11510841,I23-049107,67 ปี,หญิง,2023-12-28,1900-01-01 21:26:00,2023-12-28 21:26:00,928.0,...,18.0,1.0,18.0,0.0,0.00,0.0,0.0,0.0,1.0,0.0
503,1703957213084,EY9650,11546246,I23-050403,65 ปี,หญิง,2023-12-30,1900-01-01 00:26:00,2023-12-30 00:26:00,927.0,...,6.0,1.0,6.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0
504,1703972587046,GO3388,11546237,I23-050413,76 ปี,หญิง,2023-12-30,1900-01-01 04:43:00,2023-12-30 04:43:00,924.0,...,NaN,NaN,NaN,25.6,NaN,0.0,0.0,1.0,1.0,0.0
505,1703928233713,KY1203,11546116,I23-050381,30 ปี,หญิง,2023-12-30,1900-01-01 16:23:00,2023-12-30 16:23:00,925.0,...,28.0,NaN,NaN,22.0,28.00,0.0,0.0,0.0,0.0,0.0
506,1704022932311,HN5310,11546430,I23-050437,96 ปี,ชาย,2023-12-31,1900-01-01 18:42:00,2023-12-31 18:42:00,926.0,...,22.0,1.0,22.0,0.0,0.00,0.0,1.0,0.0,1.0,0.0

In [63]:
# # Remove records in left table that do not have info from right table
# df = df.drop(df[df['DateTimeRecord'].isna()].index)
# df[df['DateTimeRecord'].isna()]
print(tn['AdmissionID'].nunique(), tn['HN'].nunique(), tn['AN'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['AN'].nunique())

507 507 507
507 507 507
491 491

In [64]:
tn.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 159 columns):
 #    Column               Dtype
---   ------               -----
 0    AdmissionID          Int64
 1    HN                   object
 2    VN                   Int64
 3    AN                   object
 4    Age                  object
 5    Sex                  object
 6    DateRecord           datetime64[ns]
 7    TimeRecord           datetime64[ns]
 8    ICUDateTime          datetime64[ns]
 9    record_id            float64
 10   redcap_event         object
 11   icu_kku              float64
 12   h_adm_date           datetime64[ns]
 13   icu_adm_date         datetime64[ns]
 14   sex                  float64
 15   age                  float64
 16   time_to_icu          float64
 17   pdx                  float64
 18   reason_icu           float64
 19   insurance            float64
 20   insurance_oth        object
 21   postcode             float64
 22   weight               float64
 23   height               float64
 24   bmi                  float64
 25   pregnancy            float64
 26   gestatiion_wk        float64
 27   ckd                  float64
 28   ckd_stage            float64
 29   h_adm_source         float64
 30   icu_adm_source       float64
 31   elective_surg        float64
 32   arrest_bf            float64
 33   cci___1              float64
 34   cci___2              float64
 35   cci___3              float64
 36   cci___4              float64
 37   cci___5              float64
 38   cci___6              float64
 39   cci___7              float64
 40   cci___8              float64
 41   cci___9              float64
 42   cci___10             float64
 43   cci___11             float64
 44   cci___12             float64
 45   cci___13             float64
 46   cci___14             float64
 47   cci___15             float64
 48   cci___16             float64
 49   cci___17             float64
 50   cci___18             float64
 51   cci___19             float64
 52   cci___0              float64
 53   cci_total            float64
 54   lactate_24h          float64
 55   apache_3             float64
 56   sofa                 float64
 57   sap_2                float64
 58   mv_icu               float64
 59   num_ettube           float64
 60   mv_start_1           object
 61   mv_end_1             object
 62   mv_start_2           object
 63   mv_end_2             object
 64   mv_start_3           object
 65   mv_end_3             object
 66   mv_start_4           object
 67   mv_end_4             object
 68   mv_duration          float64
 69   niv                  float64
 70   ecmo                 float64
 71   iabp                 float64
 72   hemoperfusion        float64
 73   shock                float64
 74   shock_type___1       float64
 75   shock_type___2       float64
 76   shock_type___3       float64
 77   shock_type___4       float64
 78   shock_type___5       float64
 79   ino_vaso             float64
 80   vaso_start_date      object
 81   vaso_stop_date       object
 82   shock_reversal_time  float64
 83   ttm                  float64
 84   plex                 float64
 85   pan_inf              float64
 86   thrombolytic_ami     float64
 87   frailty              float64
 88   delirium             float64
 89   press_inj            float64
 90   press_inj_stage      float64
 91   cumm_fluid           float64
 92   fluid_overload       float64
 93   aki                  float64
 94   aki_onset            object
 95   aki_stage            float64
 96   aki_date             object
 97   time_icutoaki        float64
 98   aki_etio___1         float64
 99   aki_etio___2         float64
 100  aki_etio___3         float64
 101  aki_etio___4         float64
 102  aki_etio___5         float64
 103  aki_etio___6         float64
 104  aki_etio___7         float64
 105  aki_etio___8         float64
 106  aki_etio___9         float64
 107  aki_etio___10        float64
 108  aki_etio___11        float64
 109  aki_etio___12        float64
 110  fst                  float64
 111  fst_response         float64
 112  diuretic_bf          float64
 113  nephrolist_bf___1    float64
 114  nephrolist_bf___2    float64
 115  nephrolist_bf___3    float64
 116  nephrolist_bf___4    float64
 117  nephrolist_bf___5    float64
 118  nephrolist_bf___6    float64
 119  nephrolist_bf___7    float64
 120  nephrolist_bf___8    float64
 121  nephrolist_bf___9    float64
 122  nephrolist_bf___10   float64
 123  nephrolist_bf___0    float64
 124  nephrolist_af___1    float64
 125  nephrolist_af___2    float64
 126  nephrolist_af___3    float64
 127  nephrolist_af___4    float64
 128  nephrolist_af___5    float64
 129  nephrolist_af___6    float64
 130  nephrolist_af___7    float64
 131  nephrolist_af___8    float64
 132  nephrolist_af___9    float64
 133  nephrolist_af___10   float64
 134  nephrolist_af___0    float64
 135  rrt                  float64
 136  rrt_start            object
 137  rrt_type___1         float64
 138  rrt_type___2         float64
 139  rrt_type___3         float64
 140  rrt_type___4         float64
 141  rfd_28               float64
 142  icu_dc_dest          float64
 143  icu_los              float64
 144  h_dc_dest            float64
 145  h_los                float64
 146  h_mort               float64
 147  icu_mort             float64
 148  mort_28              float64
 149  surv_28              float64
 150  mort_90              float64
 151  surv_90              float64
 152  vfd_28               float64
 153  sfd_28               float64
 154  cvs                  float64
 155  neuro                float64
 156  cirrhosis            float64
 157  dm                   float64
 158  cancer               float64
dtypes: Int64(2), datetime64[ns](5), float64(133), object(19)
memory usage: 630.9+ KB

### join(intake_output, bedccr)

In [65]:
intake_output

,R_ID,AdmissionID,ICUDate,TotalIntake_Shift1,TotalIntake_Shift2,TotalIntake_Shift3,TotalIntake_24hr,TotalIntake_IV,TotalIntake_ORAL,TotalOuput_Shift1,TotalOuput_Shift2,TotalOuput_Shift3,TotalOuput_24hr,IO_Shift1,IO_Shift2,IO_Shift3,IO_24hr,LastUpdate
0,14,1704022932311,2024-01-19,992.6,1845.2,1148.2,3986.0,2946.0,1040.0,470,400.0,330,1200.0,522.6,1445.2,818.2,2786.0,20240125061958
1,27,1704022932311,2024-01-18,930.4,692.8,1106.3,2729.5,1313.5,1380.0,990,840.0,565,2395.0,-59.6,-147.2,541.3,334.5,20240125061946
2,29,1699267683825,2023-12-07,93.0,0.0,0.0,93.0,93.0,0.0,350,0.0,0,350.0,-257.0,0.0,0.0,-257.0,20240119085250
3,30,1699267683825,2023-11-06,0.0,594.9,751.1,1346.0,1346.0,0.0,0,780.0,420,1200.0,0.0,-185.1,331.1,146.0,20240119081442
4,34,1699694472553,2023-11-25,542.1,433.8,533.8,1509.7,689.7,820.0,125,530.0,550,1205.0,417.1,-96.2,-16.2,304.7,20240429091232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,1702,1690203672771,2023-07-29,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0.0,0.0,0.0,0.0,0.0,20240412094428
393,1703,1697963915143,2023-10-25,787.1,262.9,0.0,1050.0,650.0,400.0,400,800.0,0,1200.0,387.1,-537.1,0.0,-150.0,20240412100524
394,1713,1702867663447,2023-12-19,1305.1,110.6,100.0,1515.7,1385.7,130.0,255,65.0,0,320.0,1050.1,45.6,100.0,1195.7,20240413055641
395,1714,1702867663447,2023-12-18,389.3,1049.0,719.8,2158.1,1658.1,500.0,120,190.0,1050,1360.0,269.3,859.0,-330.2,798.1,20240413055644
396,1790,1675097068636,2023-03-04,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0.0,0.0,0.0,0.0,0.0,20240418100614

In [66]:
bedccr

,R_ID,AdmissionID,HN,AN,ICUDate,ICUTime,HR,BP_SYS,BP_DIA,BP_TYPE,...,BICHEM_NA,BICHEM_K,BICHEM_HCO3,BICHEM_CL,BICHEM_CA,BICHEM_PO4,BICHEM_MG,BICHEM_ALB,BICHEM_LACTATE,ICUDateTime
0,125576,1669892759015,NaN,NaN,2022-12-01,1900-01-01 18:00:00,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01 18:00:00
1,125582,1669892759015,NaN,NaN,2022-12-01,1900-01-01 19:00:00,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01 19:00:00
2,125592,1669892759015,NaN,NaN,2022-12-01,1900-01-01 20:00:00,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01 20:00:00
3,125614,1669892759015,NaN,NaN,2022-12-01,1900-01-01 21:00:00,101.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01 21:00:00
4,125627,1669892759015,NaN,NaN,2022-12-01,1900-01-01 22:00:00,97.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01 22:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118934,252740,1704022932311,NaN,NaN,2024-01-22,1900-01-01 07:00:00,110.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-22 07:00:00
118935,252752,1704022932311,NaN,NaN,2024-01-22,1900-01-01 08:00:00,112.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-22 08:00:00
118936,252765,1704022932311,NaN,NaN,2024-01-22,1900-01-01 09:00:00,111.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-22 09:00:00
118937,252778,1704022932311,NaN,NaN,2024-01-22,1900-01-01 10:00:00,112.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-22 10:00:00
118938,252791,1704022932311,NaN,NaN,2024-01-22,1900-01-01 11:00:00,113.0,NaN,NaN,ABP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-22 11:00:00

In [72]:
bi = pd.merge(bedccr, intake_output,
              on=['AdmissionID', 'ICUDate'],
              how='left', suffixes=("","_io"), indicator='exist0')

In [73]:
bi

,R_ID,AdmissionID,HN,AN,ICUDate,ICUTime,HR,BP_SYS,BP_DIA,BP_TYPE,...,TotalOuput_Shift1,TotalOuput_Shift2,TotalOuput_Shift3,TotalOuput_24hr,IO_Shift1,IO_Shift2,IO_Shift3,IO_24hr,LastUpdate,exist0
0,125576,1669892759015,NaN,NaN,2022-12-01,1900-01-01 18:00:00,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,125582,1669892759015,NaN,NaN,2022-12-01,1900-01-01 19:00:00,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,125592,1669892759015,NaN,NaN,2022-12-01,1900-01-01 20:00:00,99.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,125614,1669892759015,NaN,NaN,2022-12-01,1900-01-01 21:00:00,101.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,125627,1669892759015,NaN,NaN,2022-12-01,1900-01-01 22:00:00,97.0,NaN,NaN,NBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118934,252740,1704022932311,NaN,NaN,2024-01-22,1900-01-01 07:00:00,110.0,NaN,NaN,ABP,...,50.0,0.0,0.0,50.0,872.2,0.0,0.0,872.2,2.024022e+13,both
118935,252752,1704022932311,NaN,NaN,2024-01-22,1900-01-01 08:00:00,112.0,NaN,NaN,ABP,...,50.0,0.0,0.0,50.0,872.2,0.0,0.0,872.2,2.024022e+13,both
118936,252765,1704022932311,NaN,NaN,2024-01-22,1900-01-01 09:00:00,111.0,NaN,NaN,ABP,...,50.0,0.0,0.0,50.0,872.2,0.0,0.0,872.2,2.024022e+13,both
118937,252778,1704022932311,NaN,NaN,2024-01-22,1900-01-01 10:00:00,112.0,NaN,NaN,ABP,...,50.0,0.0,0.0,50.0,872.2,0.0,0.0,872.2,2.024022e+13,both
118938,252791,1704022932311,NaN,NaN,2024-01-22,1900-01-01 11:00:00,113.0,NaN,NaN,ABP,...,50.0,0.0,0.0,50.0,872.2,0.0,0.0,872.2,2.024022e+13,both

In [74]:
bi["exist0"].value_counts()

exist0
left_only     111045
both            7894
right_only         0
Name: count, dtype: int64

In [75]:
bi.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118939 entries, 0 to 118938
Data columns (total 121 columns):
 #    Column                    Dtype
---   ------                    -----
 0    R_ID                      int64
 1    AdmissionID               Int64
 2    HN                        float64
 3    AN                        float64
 4    ICUDate                   datetime64[ns]
 5    ICUTime                   datetime64[ns]
 6    HR                        float64
 7    BP_SYS                    object
 8    BP_DIA                    object
 9    BP_TYPE                   object
 10   MAP                       object
 11   Temp                      object
 12   RR                        object
 13   O2SAT                     object
 14   PPV                       object
 15   CVP                       object
 16   CO                        object
 17   SETTING_ModeVentilator    object
 18   SETTING_RR                float64
 19   SETTING_RR_Mech           float64
 20   SETTING_FlowTrigger       float64
 21   SETTING_TidalVolume       float64
 22   SETTING_FIO2              float64
 23   SETTING_PeakFlow          float64
 24   SETTING_PEEP              float64
 25   SETTING_PSV               float64
 26   SETTING_InspTime          float64
 27   SETTING_InspPressure      float64
 28   SETTING_IE                float64
 29   SETTING_EndFlow           float64
 30   SETTING_BiasFlow          float64
 31   SETTING_PressureRiseTime  float64
 32   SETTING_PresTrigger       float64
 33   SETTING_PSVRiseTime       float64
 34   SETTING_Phigh             float64
 35   SETTING_Plow              float64
 36   SETTING_Thigh             float64
 37   SETTING_Tlow              float64
 38   SETTING_Tsupp             float64
 39   LIVE_RR                   float64
 40   LIVE_TidalVolume          float64
 41   LIVE_PIP                  float64
 42   LIVE_DynamaicPEEPe        float64
 43   LIVE_PMEAN                float64
 44   LIVE_Pplat                float64
 45   LIVE_MV                   float64
 46   LIVE_FIO2                 float64
 47   LIVE_MV_spont             float64
 48   LIVE_TidalVolume_spont    float64
 49   LIVE_RR_spont             float64
 50   LIVE_RSBI                 float64
 51   LIVE_MV_Mech              float64
 52   LIVE_TidalVolume_Mech     float64
 53   LIVE_DynamicCompliance    float64
 54   LIVE_Raw                  float64
 55   LIVE_StaticCompliance     float64
 56   LIVE_StaticPplat          float64
 57   LIVE_StaticPEEPe          float64
 58   LIVE_StaticPEEPi          float64
 59   LIVE_PEEPe_PEEPi          float64
 60   LIVE_EE                   float64
 61   LIVE_RQ                   float64
 62   LIVE_VO2                  float64
 63   LIVE_VCO2                 float64
 64   LIVE_VO2_M2               float64
 65   LIVE_VCO2_M2              float64
 66   OUTPUT_01                 float64
 67   OUTPUT_01_DETAIL          object
 68   OUTPUT_02                 float64
 69   OUTPUT_02_DETAIL          object
 70   OUTPUT_03                 float64
 71   OUTPUT_03_DETAIL          object
 72   OUTPUT_04                 float64
 73   OUTPUT_04_DETAIL          float64
 74   OUTPUT_05                 float64
 75   OUTPUT_05_DETAIL          float64
 76   OUTPUT_06                 float64
 77   OUTPUT_06_DETAIL          float64
 78   OUTPUT_07                 float64
 79   OUTPUT_07_DETAIL          float64
 80   OUTPUT_08                 float64
 81   OUTPUT_08_DETAIL          float64
 82   ABG_PH                    float64
 83   ABG_PCO2                  float64
 84   ABG_TCO2                  float64
 85   ABG_PO2                   float64
 86   ABG_FIO2                  float64
 87   ABG_BE                    float64
 88   ABG_HCO3                  float64
 89   ABG_O2SAT                 float64
 90   BICHEM_BS                 float64
 91   BICHEM_DTX                float64
 92   BICHEM_BUN                float64
 93   BICHEM_CR                 float64
 94   BICHEM_NA                 float64
 95   BICHEM_K                  float64
 96   BICHEM_HCO3               float64
 97   BICHEM_CL                 float64
 98   BICHEM_CA                 float64
 99   BICHEM_PO4                float64
 100  BICHEM_MG                 float64
 101  BICHEM_ALB                float64
 102  BICHEM_LACTATE            float64
 103  ICUDateTime               datetime64[ns]
 104  R_ID_io                   float64
 105  TotalIntake_Shift1        float64
 106  TotalIntake_Shift2        float64
 107  TotalIntake_Shift3        float64
 108  TotalIntake_24hr          float64
 109  TotalIntake_IV            float64
 110  TotalIntake_ORAL          float64
 111  TotalOuput_Shift1         float64
 112  TotalOuput_Shift2         float64
 113  TotalOuput_Shift3         float64
 114  TotalOuput_24hr           float64
 115  IO_Shift1                 float64
 116  IO_Shift2                 float64
 117  IO_Shift3                 float64
 118  IO_24hr                   float64
 119  LastUpdate                float64
 120  exist0                    category
dtypes: Int64(1), category(1), datetime64[ns](3), float64(101), int64(1), object(14)
memory usage: 109.1+ MB

In [80]:
print(tn['AdmissionID'].nunique(), tn['HN'].nunique(), tn['AN'].nunique())
print(admission['AdmissionID'].nunique(), admission['HN'].nunique(), admission['AN'].nunique())
print(redcap['HN'].nunique(), redcap['AN'].nunique())
print(intake_output['AdmissionID'].nunique())
print(bi['AdmissionID'].nunique())

507 507 507
507 507 507
491 491
108
568

# Ohm csv

In [ ]:
df_ohm = pd.read_csv(path+"ohm_icu_merge_06-18-24.csv")

In [ ]:
df_ohm

In [ ]:
df_ohm